### ISSUE TITLE
Client id must be present in response from auth server. Google OpenIdConnect

### ISSUE THREAD

**Issue by yelhouti** [spring-projects/spring-security-oauth#1005]
Hi,
when trying to authenticate with Google using: 
token-info-uri: https://www.googleapis.com/oauth2/v3/tokeninfo
I receive the following error:

`java.lang.IllegalStateException: Client id must be present in response from auth server
	at org.springframework.util.Assert.state(Assert.java:392) ~[spring-core-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.springframework.security.oauth2.provider.token.RemoteTokenServices.loadAuthentication(RemoteTokenServices.java:114) ~[spring-security-oauth2-2.1.0.RELEASE.jar:na]
	at org.springframework.security.oauth2.client.filter.OAuth2ClientAuthenticationProcessingFilter.attemptAuthentication(OAuth2ClientAuthenticationProcessingFilter.java:112) ~[spring-security-oauth2-2.1.0.RELEASE.jar:na]
	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:212) ~[spring-security-web-4.2.1.RELEASE.jar:4.2.1.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331) ~[spring-security-web-4.2.1.RELEASE.jar:4.2.1.RELEASE]
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116) ~[spring-security-web-4.2.1.RELEASE.jar:4.2.1.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331) ~[spring-security-web-4.2.1.RELEASE.jar:4.2.1.RELEASE]
	at org.springframework.security.web.csrf.CsrfFilter.doFilterInternal(CsrfFilter.java:100) ~[spring-security-web-4.2.1.RELEASE.jar:4.2.1.RELEASE]...`
after some debugging, it seems like indeed no_client id is received in response, but I didn't find in the [specs ](http://openid.net/specs/openid-connect-core-1_0.html) where it is mentionned that the client_id must be present.
this is the token I receive: {azp=MY_CLIENT_ID.apps.googleusercontent.com, aud=MY_CLIENT_ID.apps.googleusercontent.com, sub=XXXXX, scope=https://www.googleapis.com/auth/plus.me https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile, exp=1488808147, expires_in=3589, email=my-email@gmail.com, email_verified=true, access_type=online}
as specified in the specs the "aud" field must contain the value of the client_id but they don't mention the client_id field. do you guys agree that there is a problem.
thanks

**Comment by gonzalad** [comment]
Same issue when using CXF as OAuth2 authorization server and calling CXF introspection token endpoint with an expired access token.

From OAuth 2.0 Token Introspection specification, client_id is optional (https://tools.ietf.org/html/rfc7662#section-2.2)

```
client_id
      OPTIONAL.  Client identifier for the OAuth 2.0 client that
      requested this token.
```

**Comment by gonzalad** [comment]
Isn't it a duplicate of #838 ?

**Comment by yelhouti** [comment]
Indeed, I think it is. Sorry if it's the case

**Comment by jgrandja** [comment]
Closing this issue as it's a duplicate of #838
