### ISSUE TITLE
I have a problem whit implicit RestTemplate

### ISSUE THREAD

**Issue by hdfeng265** [spring-projects/spring-security-oauth#1017]
spring-security-oauth2 : 2.0.13.RELEASE
I configed a implicit RestTemplate. 
```
@Bean
	public OAuth2RestTemplate implicitRestTemplate() {
		ImplicitResourceDetails resourceDetails = new ImplicitResourceDetails();
//		details.setId("sparklr/trusted");
		resourceDetails.setClientId("implicit");
		resourceDetails.setClientSecret("123456");
		resourceDetails.setUserAuthorizationUri("http://localhost:8080/authorization/oauth/authorize");
		resourceDetails.setAccessTokenUri("http://localhost:8080/authorization/oauth/token");
		resourceDetails.setScope(Arrays.asList("empty"));
		resourceDetails.setClientAuthenticationScheme(AuthenticationScheme.form);
//		resourceDetails.setGrantType("implicit");
		
		OAuth2RestTemplate restTemplate =  new OAuth2RestTemplate(resourceDetails, clientContext);
		
		return restTemplate;
	}
```
When i invoke template.getAccessToken(); , it throw a Exception
```
org.springframework.security.oauth2.common.exceptions.InvalidRequestException: Missing grant type
	at org.springframework.security.oauth2.common.exceptions.OAuth2ExceptionJackson2Deserializer.deserialize(OAuth2ExceptionJackson2Deserializer.java:100) ~[spring-security-oauth2-2.0.13.RELEASE.jar:na]
	at org.springframework.security.oauth2.common.exceptions.OAuth2ExceptionJackson2Deserializer.deserialize(OAuth2ExceptionJackson2Deserializer.java:33) ~[spring-security-oauth2-2.0.13.RELEASE.jar:na]
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3798) ~[jackson-databind-2.8.7.jar:2.8.7]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2922) ~[jackson-databind-2.8.7.jar:2.8.7]
	at org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.readJavaType(AbstractJackson2HttpMessageConverter.java:237) ~[spring-web-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.readInternal(AbstractJackson2HttpMessageConverter.java:217) ~[spring-web-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.http.converter.AbstractHttpMessageConverter.read(AbstractHttpMessageConverter.java:193) ~[spring-web-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.security.oauth2.client.token.OAuth2AccessTokenSupport$AccessTokenErrorHandler.handleError(OAuth2AccessTokenSupport.java:235) ~[spring-security-oauth2-2.0.13.RELEASE.jar:na]
	at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:700) ~[spring-web-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:653) ~[spring-web-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:621) ~[spring-web-4.3.7.RELEASE.jar:4.3.7.RELEASE]
```
I can get token successfully using posman, the auhorize code mode also works well

I don't know how to resolve this, can anybody help me,thank you

**Comment by richardlyc** [comment]
implicit mode get access token not supported from token endpoint.
spring oauth souce code
org.springframework.security.oauth2.provider.endpoint.TokenEndpoint

if (!StringUtils.hasText(tokenRequest.getGrantType())) {
			throw new InvalidRequestException("Missing grant type");
		}
		if (tokenRequest.getGrantType().equals("implicit")) {
			throw new InvalidGrantException("Implicit grant type not supported from token endpoint");
