### ISSUE TITLE
AuthorizationServerEndpointsConfiguration registering additional DefaultTokenServices beans

### ISSUE THREAD

**Issue by dmarcaida** [spring-projects/spring-security-oauth#1080]
I'm getting an the error which I believe is caused by `AuthorizationServerEndpointsConfiguration` registering `DefaultTokenServices` beans.

Here's the relevant portion of my configuration class:
```
@Configuration
@EnableAuthorizationServer
static class AuthorizationServerConfiguration extends AuthorizationServerConfigurerAdapter {

    @Autowired
    @Qualifier("tokenServices")
    private DefaultTokenServices tokenServices;

    @Override
    public void configure( AuthorizationServerEndpointsConfigurer endpoints ) throws Exception {
        endpoints.tokenGranter( tokenGranter() )
                .tokenServices( tokenServices );
    }
```

Here's the stacktrace:
```
     [exec] Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [javax.servlet.Filter]: Factory method 'springSecurityFilterChain' threw exception; nested exception is org.springframework.beans.factory.NoUniqueBeanDefinitionException: No qualifying bean of type 'org.springframework.security.oauth2.provider.token.ResourceServerTokenServices' available: expected single matching bean but found 3: consumerTokenServices,defaultAuthorizationServerTokenServices,tokenServices
     [exec] 	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:189)
     [exec] 	at org.springframework.beans.factory.support.ConstructorResolver$3.run(ConstructorResolver.java:582)
     [exec] 	at java.security.AccessController.doPrivileged(Native Method)
     [exec] 	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:579)
     [exec] 	... 18 more
     [exec] Caused by: org.springframework.beans.factory.NoUniqueBeanDefinitionException: No qualifying bean of type 'org.springframework.security.oauth2.provider.token.ResourceServerTokenServices' available: expected single matching bean but found 3: consumerTokenServices,defaultAuthorizationServerTokenServices,tokenServices
     [exec] 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveNamedBean(DefaultListableBeanFactory.java:1041)
     [exec] 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:345)
     [exec] 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:340)
     [exec] 	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1093)
     [exec] 	at org.springframework.security.oauth2.config.annotation.web.configuration.ResourceServerConfiguration.resolveTokenServices(ResourceServerConfiguration.java:180)
     [exec] 	at org.springframework.security.oauth2.config.annotation.web.configuration.ResourceServerConfiguration.configure(ResourceServerConfiguration.java:119)
     [exec] 	at org.springframework.security.config.annotation.web.configuration.WebSecurityConfigurerAdapter.getHttp(WebSecurityConfigurerAdapter.java:224)
     [exec] 	at org.springframework.security.config.annotation.web.configuration.WebSecurityConfigurerAdapter.init(WebSecurityConfigurerAdapter.java:315)
     [exec] 	at org.springframework.security.config.annotation.web.configuration.WebSecurityConfigurerAdapter.init(WebSecurityConfigurerAdapter.java:86)
```

Is there something I am doing wrong? Any help is appreciated. Thanks.

**Comment by dmarcaida** [comment]
Ah, fixed with `@Primary`.
