### ISSUE TITLE
JwkSetConverter should not require an alg value

### ISSUE THREAD

**Issue by npombourcq** [spring-projects/spring-security-oauth#1097]
org.springframework.security.oauth2.provider.token.store.jwk.JwkException: unknown (alg) is currently not supported.
	at org.springframework.security.oauth2.provider.token.store.jwk.JwkSetConverter.createRsaJwkDefinition(JwkSetConverter.java:157) ~[spring-security-oauth2-2.0.14.RELEASE.jar:na]
	at org.springframework.security.oauth2.provider.token.store.jwk.JwkSetConverter.createJwkDefinition(JwkSetConverter.java:126) ~[spring-security-oauth2-2.0.14.RELEASE.jar:na]
	at org.springframework.security.oauth2.provider.token.store.jwk.JwkSetConverter.convert(JwkSetConverter.java:90) ~[spring-security-oauth2-2.0.14.RELEASE.jar:na]

When trying to load https://login.microsoftonline.com/common/discovery/keys

According to https://tools.ietf.org/html/rfc7517#page-7, this parameter is optional

**Comment by jihlee** [comment]
Experienced same issue here!

**Comment by jsmusgrave** [comment]
I encountered a problem with this when trying to consume Ping Federate's JWKS.

**Comment by jgrandja** [comment]
Thanks for the report @npombourcq. The fix has been applied and is merged in master. I will also backport to 2.0.15.
