### ISSUE TITLE
spring session + oauth2 cause serialize exception

### ISSUE THREAD

**Issue by yangdailin** [spring-projects/spring-security-oauth#1115]
I use spring session + spring security oauth2 client ,but when i use @Scope(value = "session", proxyMode = ScopedProxyMode.INTERFACES)  will cause serialize exception.
my code is 
  `	@Bean
	@Scope(value = "session", proxyMode = ScopedProxyMode.INTERFACES)
	public OAuth2RestTemplate kingdeeRestTemplate() {
		DefaultOAuth2ClientContext context = new DefaultOAuth2ClientContext(
				accessTokenRequest);
		OAuth2RestTemplate template = new OAuth2RestTemplate(clientDetails(),
				context);

		List<HttpMessageConverter<?>> converters = new ArrayList<HttpMessageConverter<?>>();
		converters.add(new KingdeeMappingJackson2HttpMessageConverter());
		AuthorizationCodeAccessTokenProvider tokenProvider = new AuthorizationCodeAccessTokenProvider();
		tokenProvider.setMessageConverters(converters);
		AccessTokenProvider accessTokenProvider = new AccessTokenProviderChain(
				Arrays.<AccessTokenProvider> asList(tokenProvider));
		template.setAccessTokenProvider(accessTokenProvider);
		return template;
	}`
and exception is
`org.springframework.data.redis.serializer.SerializationException: Cannot serialize; nested exception is org.springframework.core.serializer.support.SerializationFailedException: Failed to serialize object using DefaultSerializer; nested exception is java.lang.IllegalArgumentException: DefaultSerializer requires a Serializable payload but received an object of type [org.springframework.security.oauth2.client.OAuth2RestTemplate]
	at org.springframework.data.redis.serializer.JdkSerializationRedisSerializer.serialize(JdkSerializationRedisSerializer.java:92)
	at org.springframework.data.redis.core.AbstractOperations.rawHashValue(AbstractOperations.java:168)
	at org.springframework.data.redis.core.DefaultHashOperations.putAll(DefaultHashOperations.java:129)
	at org.springframework.data.redis.core.DefaultBoundHashOperations.putAll(DefaultBoundHashOperations.java:86)
	at org.springframework.session.data.redis.RedisOperationsSessionRepository$RedisSession.saveDelta(RedisOperationsSessionRepository.java:778)
	at org.springframework.session.data.redis.RedisOperationsSessionRepository$RedisSession.access$000(RedisOperationsSessionRepository.java:670)
..........................`

because I use spring session to achieve session cluster, so if I use @Scope(value= 'session'), this will save redis after serialize. but OAuth2RestTemplate is not serialize. is any solution to avoid this?

**Comment by jgrandja** [comment]
Closing this issue as explained in this [comment](https://github.com/spring-projects/spring-session/issues/829#issuecomment-317955276)
