### ISSUE TITLE
Message converters initialization in OAuth2AccessTokenSupport is not thread-safe

### ISSUE THREAD

**Issue by lukasz-kusnierz** [spring-projects/spring-security-oauth#1194]
I have experienced several exceptions like this:

```
Caused by: java.util.ConcurrentModificationException: null
    at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
    at java.util.ArrayList$Itr.next(ArrayList.java:851)
    at org.springframework.web.client.HttpMessageConverterExtractor.extractData(HttpMessageConverterExtractor.java:87)
    at org.springframework.security.oauth2.client.token.OAuth2AccessTokenSupport$2.extractData(OAuth2AccessTokenSupport.java:134)
    at org.springframework.security.oauth2.client.token.OAuth2AccessTokenSupport$2.extractData(OAuth2AccessTokenSupport.java:128)
    at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:622)
    at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:588)
    at org.springframework.security.oauth2.client.token.OAuth2AccessTokenSupport.retrieveToken(OAuth2AccessTokenSupport.java:137)
    at org.springframework.security.oauth2.client.token.grant.client.ClientCredentialsAccessTokenProvider.obtainAccessToken(ClientCredentialsAccessTokenProvider.java:44)
    at org.springframework.security.oauth2.client.token.AccessTokenProviderChain.obtainNewAccessTokenInternal(AccessTokenProviderChain.java:148)
    at org.springframework.security.oauth2.client.token.AccessTokenProviderChain.obtainAccessToken(AccessTokenProviderChain.java:121)
    at org.springframework.security.oauth2.client.OAuth2RestTemplate.acquireAccessToken(OAuth2RestTemplate.java:221)
    at org.springframework.security.oauth2.client.OAuth2RestTemplate.getAccessToken(OAuth2RestTemplate.java:173)
    at org.springframework.security.oauth2.client.OAuth2RestTemplate.createRequest(OAuth2RestTemplate.java:105)
    at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:615)
    at org.springframework.security.oauth2.client.OAuth2RestTemplate.doExecute(OAuth2RestTemplate.java:128)
    at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:580)
    at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:498)
```
The cause for this seems to be how `OAuth2AccessTokenSupport.messageConverters` list is initialized:

```java
protected RestOperations getRestTemplate() {
	if (restTemplate == null) {
		synchronized (this) {
			if (restTemplate == null) {
				RestTemplate restTemplate = new RestTemplate();
				restTemplate.setErrorHandler(getResponseErrorHandler());
				restTemplate.setRequestFactory(requestFactory);
				restTemplate.setInterceptors(interceptors);
				this.restTemplate = restTemplate;
			}
		}
	}
	if (messageConverters == null) {
		setMessageConverters(new RestTemplate().getMessageConverters());
	}
	return restTemplate;
}

public void setMessageConverters(List<HttpMessageConverter<?>> messageConverters) {
	this.messageConverters = new ArrayList<HttpMessageConverter<?>>(messageConverters);
	this.messageConverters.add(new FormOAuth2AccessTokenMessageConverter());
	this.messageConverters.add(new FormOAuth2ExceptionHttpMessageConverter());
}
```

Initialization is lazy, but not synchronized in any way. Therefore, `HttpMessageConverterExtractor` (created in `OAuth2AccessTokenSupport.getResponseExtractor`) ends up iterating over a list modified by another thread. This means all token providers extending `OAuth2AccessTokenSupport` are not thread-safe for a short moment before fully initialized.

I was able to workaround this by overriding and substituting token provider:

```java
class ThreadSafeClientCredentialsAccessTokenProvider extends ClientCredentialsAccessTokenProvider {

	private RestOperations restOperations;

	@Override
	protected RestOperations getRestTemplate() {
		if (null == this.restOperations) {
			synchronized (this) {
				if (null == this.restOperations) {
					this.restOperations = super.getRestTemplate();
				}
			}
		}
		return this.restOperations;
	}
}
```
In my workaround both `RestTemplate` creation and `messageConverters` initialization is synchronized.

**Comment by xzhangvelo** [comment]
I noticed the exactly same behaviour in spring-security-oauth2 **2.3.5.RELEASE**

Just wondering any downside to make it thread safe or there are other solutions? Is the above workaround affects the performance?
