### ISSUE TITLE
/oauth/token can throw a a unique key constraint error under load

### ISSUE THREAD

**Issue by xenoterracide** [spring-projects/spring-security-oauth#1202]
Our first issue was #463, we corrected, that, but while testing the fix, #1200 and this was discovered. 

using `oauth2:2.0.14`

```
Calebs-MacBook-Pro:dex calebcushing$ parallel -j10 'curl -X POST --header "Content-Type: application/x-www-form-urlencoded" --header "Accept: application/json" -d "grant_type=password&client_id=O88trBJRSemI92Lu_CuC3Q&username=ou9xput8rraa7cedkdohxa&password=sna1C8jSSOK3dAiurGXQTA" --silent http://localhost:8080/oauth/token; echo -e "\n"' ::: {1..1000} |grep error | sort | uniq -c
   8 {"error":"server_error","error_description":"PreparedStatementCallback; SQL [insert into oauth_access_token (token_id, token, authentication_id, user_name, client_id, authentication, refresh_token) values (?, ?, ?, ?, ?, ?, ?)]; ORA-00001: unique constraint (DEX_DEV_USER.PK_OAT_AID) violated\n; nested exception is java.sql.SQLIntegrityConstraintViolationException: ORA-00001: unique constraint (DEX_DEV_USER.PK_OAT_AID) violated\n"}
  97 {"error":"server_error","error_description":"PreparedStatementCallback; uncategorized SQLException for SQL [select token_id, authentication from oauth_access_token where token_id = ?]; SQL state [72000]; error code [1555]; ORA-01555: snapshot too old: rollback segment number  with name &quot;&quot; too small\nORA-22924: snapshot too old\n; nested exception is java.sql.SQLException: ORA-01555: snapshot too old: rollback segment number  with name &quot;&quot; too small\nORA-22924: snapshot too old\n"}
```

as you can see 2 different errors are returns, 1 is a unique key violation, and the other has to do with oracle segments. I'm not sure I currently understand the latter, so I'll be investigating to see if it happens in our staging environment. This suggests that the first happens less than 1% of the time, and the latter happens about 10% of the time.

unfortunately due to poor exception logging, it's hard to figure out what more is going into this stack. #1211 

```
[INFO ] [11:51:10] [http-nio-8080-exec-3] endpoint.TokenEndpoint:166 - (:O88trBJRSemI92Lu_CuC3Q) - Handling error: UncategorizedSQLException, PreparedStatementCallback; uncategorized SQLException for SQL [select token_id, authentication from oauth_access_token where token_id = ?]; SQL state [72000]; error code [1555]; ORA-01555: snapshot too old: rollback segment number  with name "" too small_ORA-22924: snapshot too old_; nested exception is java.sql.SQLException: ORA-01555: snapshot too old: rollback segment number  with name "" too small_ORA-22924: snapshot too old_
```

I have rarely been able to produce the exceptions in production, they happen less than 1% of the time. More frequent in dev, possibly because the actual errors might be caused by some misconfiguration of oracle xe, it's different version (from prod, 11 vs 12), or the fact that it's OS X -> VirtualBOX -> Docker locally.

However, it does seem like `SQLIntegrityConstraintViolationException` could be handled better if it does throw. Restfully I would think that this would throw a 401 conflict, but I'm not sure if the OAuth Spec specifies. 

the information exposure (#1200) is still unacceptable for either exception but that's a different issue from actually not having the exceptions throw, or making them behave better if they do.

**Comment by jgrandja** [comment]
Duplicate of #1200

**Comment by xenoterracide** [comment]
@jgrandja so I probably wrote this sloppily, but you don't think there should be special handling in the library of a unique key contstraint violation? or more prevention of that happening? not talking about the exception print in this case so much as, how is this happening? is oauth not selecting for update? should it catch a unique constraint and try again? etc.

**Comment by kopax** [comment]
It this supposed to fix #1242 ? I have tried version 2.2.1 and I am still experience this issue.

**Comment by xenoterracide** [comment]
#1242 sound like the same issue I was attempting to report here, though no fix for this was implemented, and I believe this was inappropriately marked as a duplicate.

**Comment by kopax** [comment]
I confirm this erreur is still existing and I can easely reproduce it. 

Is it possible to reopen this?

**Comment by jgrandja** [comment]
@kopax @xenoterracide Re-opening this issue and will look into this further.

**Comment by jgrandja** [comment]
@kopax Would you be able to provide me a sample that reproduces this error? This would be very helpful to allow for efficient troubleshooting.

**Comment by kopax** [comment]
Hi @jgrandja. You have my confirmation that I will give you a reproduction repository before Xmas with ll the test environment it needs to identify the problem.

Thanks a lot for picking up the case.

**Comment by kopax** [comment]
@jgrandja Here you are.

You will find the repro here:

- https://github.com/kopax/spring-security-oauth-issues-1202
- https://github.com/kopax/spring-security-oauth-issues-1202-client

Issue [#1202](https://github.com/spring-projects/spring-security-oauth/issues/1202)
=============

I want to request resource data asynchronously.

These are my endpoints : 

An __anonymous user__ should be able to access only these endpoints

- http://localhost:8080/login
- http://localhost:8080/logout
- http://localhost:8080/ping

An __authenticated user__ with `ROLE_USER` should be able to access only these endpoints

- http://localhost:8080/oauth/authorize
- http://localhost:8080/oauth/token

An __authenticated user using a jwt__ can access these endpoints

- http://localhost:8080/**
- http://localhost:8080/roles

I am executing a list of request to a OAuth secured endpoint in two modes:

- synchronously
- asynchronously

Reproduction
------------

You will need two project, the spring backend and a nodejs rest client: 

Requirement:

- Java JDK 8
- Node 4 or later
- Npm 4 or later

1. Clone the project

        mkdir -p ~/tmp && cd ~/tmp && git clone https://github.com/kopax/spring-security-oauth-issues-1202 && cd spring-security-oauth-issues-1202

2. start the server

        ./gradlew build --info && java -jar $(find build/libs -name "*.jar" -type f | xargs ls -tr | tail -1) --spring.profiles.active=default

3. Open a new terminal and clone the client test project

        mkdir -p ~/tmp && cd ~/tmp && git clone git@github.com:kopax/spring-security-oauth-issues-1202-client.git && cd spring-security-oauth-issues-1202-client && npm install
        
4. Run the client test synchronously (always succeed)

        npm run roles
        # this will prompt for credential which are already set for you, just press enter till the end
        
5. Run the client test asynchronously (mostly will fail)
    
        npm run roles
        # this will prompt for credential which are already set for you
        # press enter till the question "ASYNC MODE" where you MUST choose "YES"
        
6. Clean the reproduction

        rm -rf ~/tmp 
 
Expected
--------

http status code `200` 

Result
------

```bash
Handling error: DuplicateKeyException, PreparedStatementCallback; SQL [insert into oauth_access_token (token_id, token, authentication_id, user_name, client_id, authentication, refresh_token) values (?, ?, ?, ?, ?, ?, ?)]; Unique index or primary key violation: "PRIMARY_KEY_D ON PUBLIC.OAUTH_ACCESS_TOKEN(AUTHENTICATION_ID) VALUES ('b762270ce877e5b49c8f9305e3eb0ab1', 14)"; SQL statement:
insert into oauth_access_token (token_id, token, authentication_id, user_name, client_id, authentication, refresh_token) values (?, ?, ?, ?, ?, ?, ?) [23505-194]; nested exception is org.h2.jdbc.JdbcSQLException: Unique index or primary key violation: "PRIMARY_KEY_D ON PUBLIC.OAUTH_ACCESS_TOKEN(AUTHENTICATION_ID) VALUES ('b762270ce877e5b49c8f9305e3eb0ab1', 14)"; SQL statement:
insert into oauth_access_token (token_id, token, authentication_id, user_name, client_id, authentication, refresh_token) values (?, ?, ?, ?, ?, ?, ?) [23505-194]
org.springframework.dao.DuplicateKeyException: PreparedStatementCallback; SQL [insert into oauth_access_token (token_id, token, authentication_id, user_name, client_id, authentication, refresh_token) values (?, ?, ?, ?, ?, ?, ?)]; Unique index or primary key violation: "PRIMARY_KEY_D ON PUBLIC.OAUTH_ACCESS_TOKEN(AUTHENTICATION_ID) VALUES ('b762270ce877e5b49c8f9305e3eb0ab1', 14)"; SQL statement:
insert into oauth_access_token (token_id, token, authentication_id, user_name, client_id, authentication, refresh_token) values (?, ?, ?, ?, ?, ?, ?) [23505-194]; nested exception is org.h2.jdbc.JdbcSQLException: Unique index or primary key violation: "PRIMARY_KEY_D ON PUBLIC.OAUTH_ACCESS_TOKEN(AUTHENTICATION_ID) VALUES ('b762270ce877e5b49c8f9305e3eb0ab1', 14)"; SQL statement:
insert into oauth_access_token (token_id, token, authentication_id, user_name, client_id, authentication, refresh_token) values (?, ?, ?, ?, ?, ?, ?) [23505-194]
	at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:239)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:73)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:655)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:876)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:937)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:942)
	at org.springframework.security.oauth2.provider.token.store.JdbcTokenStore.storeAccessToken(JdbcTokenStore.java:148)
	at org.springframework.security.oauth2.provider.token.DefaultTokenServices.createAccessToken(DefaultTokenServices.java:122)
	at org.springframework.security.oauth2.provider.token.AbstractTokenGranter.getAccessToken(AbstractTokenGranter.java:70)
	at org.springframework.security.oauth2.provider.token.AbstractTokenGranter.grant(AbstractTokenGranter.java:65)
	at org.springframework.security.oauth2.provider.CompositeTokenGranter.grant(CompositeTokenGranter.java:38)
	at org.springframework.security.oauth2.config.annotation.web.configurers.AuthorizationServerEndpointsConfigurer$4.grant(AuthorizationServerEndpointsConfigurer.java:561)
	at org.springframework.security.oauth2.provider.endpoint.TokenEndpoint.postAccessToken(TokenEndpoint.java:132)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:872)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:661)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:317)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:127)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:91)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:114)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:137)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:170)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.authentication.www.BasicAuthenticationFilter.doFilterInternal(BasicAuthenticationFilter.java:215)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:64)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:214)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:177)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:347)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:263)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:108)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:81)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.session.web.http.SessionRepositoryFilter.doFilterInternal(SessionRepositoryFilter.java:167)
	at org.springframework.session.web.http.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:80)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.common.servlet.filter.CORSFilter.doFilter(CORSFilter.java:40)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1459)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.h2.jdbc.JdbcSQLException: Unique index or primary key violation: "PRIMARY_KEY_D ON PUBLIC.OAUTH_ACCESS_TOKEN(AUTHENTICATION_ID) VALUES ('b762270ce877e5b49c8f9305e3eb0ab1', 14)"; SQL statement:
insert into oauth_access_token (token_id, token, authentication_id, user_name, client_id, authentication, refresh_token) values (?, ?, ?, ?, ?, ?, ?) [23505-194]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.index.BaseIndex.getDuplicateKeyException(BaseIndex.java:103)
	at org.h2.mvstore.db.MVSecondaryIndex.checkUnique(MVSecondaryIndex.java:231)
	at org.h2.mvstore.db.MVSecondaryIndex.add(MVSecondaryIndex.java:190)
	at org.h2.mvstore.db.MVTable.addRow(MVTable.java:707)
	at org.h2.command.dml.Insert.insertRows(Insert.java:156)
	at org.h2.command.dml.Insert.update(Insert.java:114)
	at org.h2.command.CommandContainer.update(CommandContainer.java:101)
	at org.h2.command.Command.executeUpdate(Command.java:258)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:160)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:146)
	at org.springframework.jdbc.core.JdbcTemplate$2.doInPreparedStatement(JdbcTemplate.java:883)
	at org.springframework.jdbc.core.JdbcTemplate$2.doInPreparedStatement(JdbcTemplate.java:876)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:639)
	... 104 common frames omitted
Socket: [org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper@4f2cecca:org.apache.tomcat.util.net.NioChannel@486d5308:java.nio.channels.SocketChannel[connected local=/127.0.0.1:8080 remote=/127.0.0.1:39524]], Read from buffer: [0]
Received [GET /roles?organization=kopax&siteServiceIds=6000 HTTP/1.1
accept: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsibXlhcHAvYXBpIl0sInVzZXJfbmFtZSI6ImFkbWluIiwic2NvcGUiOlsidHJ1c3QiLCJyZWFkIiwid3JpdGUiXSwiZXhwIjoxNTEzMDQ0MDA1LCJhdXRob3JpdGllcyI6WyJST0xFX01BTkFHRVIiLCJST0xFX0FETUlOIiwiUk9MRV9VU0VSIl0sImp0aSI6IjE3YjgxNWNhLTc5NmMtNGI4Ni05YjZjLWY3YzgzMjA0NzczOSIsImNsaWVudF9pZCI6Im15Zmlyc3RhcHAiLCJ1c2VybmFtZSI6ImFkbWluIn0.NQx11bSgHKv3dHYaLydyo7kwqsiydSLTZPvRaSXsXl4
content-type: application/json
cookie: XSRF-TOKEN=d1111657-c1b2-471a-99aa-a338c23dd8b5; JSESSIONID=983615fd-d156-4072-ac18-efd365345036
accept-encoding: gzip,deflate
user-agent: node-fetch/1.0 (+https://github.com/bitinn/node-fetch)
connection: close
Host: localhost:8080

```


Useful information:
===================

Spring server:

- http://localhost:8080/

Security account (cookie):

- username: `admin`
- password: `verysecret`

OAuth account (jwt):

- client_id: `myfirstapp`
- client_secret: `test`
- redirect_uri: `http://localhost:8080/`
- access_token_uri: `http://localhost:8080/oauth/token`
- authorization_uri: `http://localhost:8080/oauth/authorize`
- authorization_grant: `code`
- redirect_uri: `http://localhost:8080`

Can you please keep us updated ?

**Comment by jgrandja** [comment]
@kopax Thank you for the sample and the detailed instructions. I'll look into this today.

**Comment by jgrandja** [comment]
@kopax Please see this [comment](https://github.com/spring-projects/spring-security-oauth/issues/1242#issuecomment-351516168) for a detailed explanation.

**Comment by Yasgur99** [comment]
`"PreparedStatementCallback; SQL [insert into oauth_access_token (token_id, token, authentication_id, user_name, client_id, authentication, refresh_token) values (?, ?, ?, ?, ?, ?, ?)]; Duplicate entry &#39;e13b031fcf7cea04f50bca8513dbc97c&#39; for key &#39;PRIMARY&#39;; nested exception is java.sql.SQLIntegrityConstraintViolationException: Duplicate entry &#39;e13b031fcf7cea04f50bca8513dbc97c&#39; for key &#39;PRIMARY&#39;"`

I can reproduce this when i make one call to oauth to create token, followed by a call in a different context also getting a new token from scratch, and the old one tries to refresh with the old refresh token but a new one is issued to the second caller getting a new token from scratch which creates this exception for me
