### ISSUE TITLE
JwtAccessTokenConverter - crypto.sign.Signer ClassNotFoundException

### ISSUE THREAD

**Issue by merihsakarya** [spring-projects/spring-security-oauth#1372]
I tried to update version of my spring-boot project to 2.0.2.RELEASE and OAuth2 2.3.3.RELEASE.
It fails when it creates a new instance of JwtAccessTokenConverter class.

> JwtAccessTokenConverter converter = new JwtAccessTokenConverter();

ERROR :
```
Caused by: java.lang.ClassNotFoundException: org.springframework.security.jwt.crypto.sign.Signer
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 66 common frames omitted
```

CODE :
```
@Bean
protected JwtAccessTokenConverter jwtAccessTokenConverter() {
	KeyStoreKeyFactory keyStoreKeyFactory = new KeyStoreKeyFactory(new ClassPathResource("jwt.jks"), "mySecretKey".toCharArray());
	JwtAccessTokenConverter converter = new JwtAccessTokenConverter();
	converter.setKeyPair(keyStoreKeyFactory.getKeyPair("jwt"));
	return converter;
}
```

pom.xml :
```
<parent>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-starter-parent</artifactId>
	<version>2.0.2.RELEASE</version>
	<relativePath /><!-- lookup parent from repository -->
</parent>

<dependency>
	<groupId>org.springframework.security.oauth</groupId>
	<artifactId>spring-security-oauth2</artifactId>
	<version>2.3.3.RELEASE</version>
</dependency>
```

**Comment by liuyao61** [comment]
Hi merihsakarya,

You need this dependency: org.springframework.security:spring-security-jwt

**Comment by JeyhunGasimov** [comment]
@liuyao61 thanks

**Comment by rwinch** [comment]
This is part of
