### ISSUE TITLE
org.springframework.security.jwt.crypto.sign.RSAVerifier throwing wrong extended Exception

### ISSUE THREAD

**Issue by Tandolf** [spring-projects/spring-security-oauth#1375]
If verification in [RsaVerifer.class](https://github.com/spring-projects/spring-security-oauth/blob/master/spring-security-jwt/src/main/java/org/springframework/security/jwt/crypto/sign/RsaVerifier.java) fails, the `RsaVerifier#verify` method will throw a [InvalidSignatureException.class](https://github.com/spring-projects/spring-security-oauth/blob/master/spring-security-jwt/src/main/java/org/springframework/security/jwt/crypto/sign/InvalidSignatureException.java)

This exception doesn't extend the `org.springframework.security.oauth2.common.exceptions.OAuth2Exception.class` so it will not get caught in the `OAuth2AuthenticationProcessingFilter.class`. Instead this exception gets thrown right out in to the wild, big bad, internet as a 500 Internal Server Error.

Our workaround at the moment is to register a CustomAuthenticationManager in the Context that will intercept this exception and catch/rethrow a new subclassed exception that extends `org.springframework.security.oauth2.common.exceptions.OAuth2Exception.class` and maps it to a 401 UNAUTHORIZED status.

Another thing to mention is that the `RsaVerifier.class` implements the interface `SignatureVerifier.class` but there is no way in the code to implement your own SignatureVerifier and jack it into the flow and do your own custom verification of the signing.

**Comment by Leonab** [comment]
Any updates on this?

**Comment by asbachb** [comment]
@jgrandja can you share your thoughts in this issue?

**Comment by jgrandja** [comment]
@Tandolf 
`RsaVerifier` is intended to throw `InvalidSignatureException` for invalid signatures. As well, `InvalidSignatureException` is not meant to extend from `OAuth2Exception` since JWT can be used outside of OAuth 2.0. So the design here is correct.

Looking at `JwtAccessTokenConverter.decode()`, I see that it catches `Exception` and re-throws `InvalidTokenException` (extends `OAuth2Exception`) so I don't see how a 500 results here? Can you please provide more details.

**Comment by asbachb** [comment]
@jgrandja we have the same problem. Maybe the combination of Spring Security 5 and spring-security-oauth2 is the problem?

```
org.springframework.security.jwt.crypto.sign.InvalidSignatureException: RSA Signature did not match content
	at org.springframework.security.jwt.crypto.sign.RsaVerifier.verify(RsaVerifier.java:55) ~[spring-security-jwt-1.0.11.RELEASE.jar:?]
	at org.springframework.security.jwt.JwtImpl.verifySignature(JwtHelper.java:287) ~[spring-security-jwt-1.0.11.RELEASE.jar:?]
	at org.springframework.security.oauth2.provider.token.store.jwk.JwkVerifyingJwtAccessTokenConverter.decode(JwkVerifyingJwtAccessTokenConverter.java:122) ~[spring-security-oauth2-2.3.7.RELEASE.jar:?]
	at org.springframework.security.oauth2.provider.token.store.JwtTokenStore.convertAccessToken(JwtTokenStore.java:88) ~[spring-security-oauth2-2.3.7.RELEASE.jar:?]
	at org.springframework.security.oauth2.provider.token.store.JwtTokenStore.readAccessToken(JwtTokenStore.java:80) ~[spring-security-oauth2-2.3.7.RELEASE.jar:?]
	at org.springframework.security.oauth2.provider.token.store.jwk.JwkTokenStore.readAccessToken(JwkTokenStore.java:212) ~[spring-security-oauth2-2.3.7.RELEASE.jar:?]
	at org.springframework.security.oauth2.provider.token.DefaultTokenServices.loadAuthentication(DefaultTokenServices.java:229) ~[spring-security-oauth2-2.3.7.RELEASE.jar:?]
	at org.springframework.security.oauth2.provider.authentication.OAuth2AuthenticationManager.authenticate(OAuth2AuthenticationManager.java:83) ~[spring-security-oauth2-2.3.7.RELEASE.jar:?]
	at org.springframework.security.oauth2.provider.authentication.OAuth2AuthenticationProcessingFilter.doFilter(OAuth2AuthenticationProcessingFilter.java:150) ~[spring-security-oauth2-2.3.7.RELEASE.jar:?]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) ~[spring-security-web-5.2.0.RELEASE.jar:5.2.0.RELEASE]
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116) ~[spring-security-web-5.2.0.RELEASE.jar:5.2.0.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) ~[spring-security-web-5.2.0.RELEASE.jar:5.2.0.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:103) ~[spring-web-5.2.0.RELEASE.jar:5.2.0.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) ~[spring-security-web-5.2.0.RELEASE.jar:5.2.0.RELEASE]
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105) ~[spring-security-web-5.2.0.RELEASE.jar:5.2.0.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) ~[spring-security-web-5.2.0.RELEASE.jar:5.2.0.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:103) ~[spring-web-5.2.0.RELEASE.jar:5.2.0.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) ~[spring-security-web-5.2.0.RELEASE.jar:5.2.0.RELEASE]
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:215) ~[spring-security-web-5.2.0.RELEASE.jar:5.2.0.RELEASE]
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:178) ~[spring-security-web-5.2.0.RELEASE.jar:5.2.0.RELEASE]
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:358) ~[spring-web-5.2.0.RELEASE.jar:5.2.0.RELEASE]
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:271) ~[spring-web-5.2.0.RELEASE.jar:5.2.0.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.27.jar:9.0.27]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.27.jar:9.0.27]
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:712) ~[tomcat-embed-core-9.0.27.jar:9.0.27]
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:461) ~[tomcat-embed-core-9.0.27.jar:9.0.27]
	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:384) ~[tomcat-embed-core-9.0.27.jar:9.0.27]
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:312) ~[tomcat-embed-core-9.0.27.jar:9.0.27]
	at org.apache.catalina.core.StandardHostValve.custom(StandardHostValve.java:394) [tomcat-embed-core-9.0.27.jar:9.0.27]
	at org.apache.catalina.core.StandardHostValve.status(StandardHostValve.java:253) [tomcat-embed-core-9.0.27.jar:9.0.27]
	at org.apache.catalina.core.StandardHostValve.throwable(StandardHostValve.java:348) [tomcat-embed-core-9.0.27.jar:9.0.27]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:173) [tomcat-embed-core-9.0.27.jar:9.0.27]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [tomcat-embed-core-9.0.27.jar:9.0.27]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) [tomcat-embed-core-9.0.27.jar:9.0.27]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) [tomcat-embed-core-9.0.27.jar:9.0.27]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408) [tomcat-embed-core-9.0.27.jar:9.0.27]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-embed-core-9.0.27.jar:9.0.27]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:861) [tomcat-embed-core-9.0.27.jar:9.0.27]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1579) [tomcat-embed-core-9.0.27.jar:9.0.27]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-9.0.27.jar:9.0.27]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-9.0.27.jar:9.0.27]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by jgrandja** [comment]
@asbachb Based on the stacktrace, the signature is invalid.

I'm not sure what you mean by 

> Maybe the combination of Spring Security 5 and spring-security-oauth2 is the problem?

**Comment by Tandolf** [comment]
**This issue was written 18 months ago**

and the code base i was working on when i wrote this issue was at my former employer.

I have no idea how this and other codebases have evolved since then and i donät have time to provide more information than the information i provided 18 months ago.

So will close this issue due to fact of getting addressed about 17 months too late.

**Comment by asbachb** [comment]
@jgrandja It's not the point that the signature is incorrect. The point is that it's not converted into an exception which is handled by Spring Security 5 and caused by that shown as an http 500 not a 401.

> I'm not sure what you mean by
> 
> > Maybe the combination of Spring Security 5 and spring-security-oauth2 is the problem?

My interpretation of https://github.com/spring-projects/spring-security/wiki/OAuth-2.0-Features-Matrix is that the combiation of `Spring Security` and `Spring Security OAuth` should not be used. When using Spring Security the OAuth module should be used.
But that's only my guess. Since the entire "Spring Security" world is quite confusing for me.
