### ISSUE TITLE
Use AuthenticationManager, have error about java.lang.IllegalStateException: No ServletContext set

### ISSUE THREAD

**Issue by Lguangqing** [spring-projects/spring-security-oauth#1392]
spring-boot-starter-parent 1.5.13.RELEASE
spring-cloud-starter-oauth2 1.2.2.RELEASE
If I were in the main configuration in the class of start WebSecurityConfigurerAdapter and AuthorizationServerConfigurerAdapter, can normal boot, as follows
```
@SpringBootApplication
@EnableDiscoveryClient
public class AuthCenterApplication {

    public static void main(String[] args) {
        SpringApplication.run(AuthCenterApplication.class, args);
    }

    @Configuration
    @EnableWebSecurity
    protected static class webSecurityConfig extends WebSecurityConfigurerAdapter {

        @Autowired
        private SysUserDetailsService userDetailsService;

        @Override
        protected void configure(HttpSecurity http) throws Exception {
            // @formatter:off
            http
                    .authorizeRequests().anyRequest().authenticated()
                    .and()
                    .csrf().disable();
            // @formatter:on
        }

        @Override
        public void configure(WebSecurity webSecurity) throws Exception {
            webSecurity
                    .ignoring()
                    // All of Spring Security will ignore the requests
                    .antMatchers("/v2/api-docs" , "/druid/**" );
        }

        @Override
        protected void configure(AuthenticationManagerBuilder auth) throws Exception {
            auth.userDetailsService(userDetailsService)
                    .passwordEncoder(new BCryptPasswordEncoder());
        }

        @Override
        @Bean
        public AuthenticationManager authenticationManagerBean() throws Exception {
            return super.authenticationManagerBean();
        }
    }

    @Configuration
    @EnableAuthorizationServer
    protected static class OAuth2AuthorizationConfig extends AuthorizationServerConfigurerAdapter {

        private TokenStore tokenStore = new InMemoryTokenStore();

        @Autowired
        @Qualifier("authenticationManagerBean" )
        private AuthenticationManager authenticationManager;

        @Autowired
        private SysUserDetailsService userDetailsService;

        @Autowired
        private Environment env;

        @Override
        public void configure(ClientDetailsServiceConfigurer clients) throws Exception {

            // TODO persist clients details

            // @formatter:off
            clients.inMemory()
                    .withClient("browser" )
                    .authorizedGrantTypes("refresh_token" , "password" )
                    .scopes("ui" )
                    .accessTokenValiditySeconds(18000) // 5 hour
                    .refreshTokenValiditySeconds(2592000) // 30 days
                    .and()
                    .withClient("account-service" )
                    .secret(env.getProperty("ACCOUNT_SERVICE_PASSWORD" , "user" ))
                    .authorizedGrantTypes("client_credentials" , "refresh_token" )
                    .scopes("server" )
                    .and()
                    .withClient("sms-service" )
                    .secret(env.getProperty("SMS_SERVICE_PASSWORD" , "user" ))
                    .authorizedGrantTypes("client_credentials" , "refresh_token" )
                    .scopes("server" )
                    .and()
                    .withClient("charge-service" )
                    .secret(env.getProperty("CHARGE_SERVICE_PASSWORD" , "user" ))
                    .authorizedGrantTypes("client_credentials" , "refresh_token" )
                    .scopes("server" )
                    .and()
                    .withClient("delivery-service" )
                    .secret(env.getProperty("DELIVERY_SERVICE_PASSWORD" , "user" ))
                    .authorizedGrantTypes("client_credentials" , "refresh_token" )
                    .scopes("server" )
                    .and()
                    .withClient("app-service" )
                    .secret(env.getProperty("APP_SERVICE_PASSWORD" , "user" ))
                    .authorizedGrantTypes("client_credentials" , "refresh_token" )
                    .scopes("server" )
                    .and()
                    .withClient("monitoring-service" )
                    .secret(env.getProperty("MONITORING_SERVICE_PASSWORD" , "user" ))
                    .authorizedGrantTypes("client_credentials" , "refresh_token" )
                    .scopes("server" )
            ;
            // @formatter:on
        }

        @Override
        public void configure(AuthorizationServerEndpointsConfigurer endpoints) throws Exception {
            endpoints
                    .tokenStore(tokenStore)
                    .authenticationManager(authenticationManager)
                    .userDetailsService(userDetailsService);
        }

        @Override
        public void configure(AuthorizationServerSecurityConfigurer oauthServer) throws Exception {
            oauthServer
                    .tokenKeyAccess("permitAll()" )
                    .checkTokenAccess("isAuthenticated()" );
        }
    }

    
     /* @Description : security 错误信息本地化
     * ---------------------------------
     * @Author : Liang.Guangqing
     * @Date : Create in 2018/2/5 9:09
    **/

    @Bean
    public MessageSource messageSource() {
        Locale.setDefault(Locale.SIMPLIFIED_CHINESE);
        ReloadableResourceBundleMessageSource messageSource = new ReloadableResourceBundleMessageSource();
        messageSource.addBasenames("classpath:/messages/messages" );
        return messageSource;
    }

}
```
But let me write the configuration separately,
**AuthorizationServerConfig**
```
@Configuration
@EnableAuthorizationServer
public class AuthorizationServerConfig extends AuthorizationServerConfigurerAdapter {

    private TokenStore tokenStore = new InMemoryTokenStore();

    @Autowired
    private AuthenticationManager authenticationManager;

    @Autowired
    private SysUserDetailsService userDetailsService;

    @Autowired
    private Environment env;

    @Override
    public void configure(ClientDetailsServiceConfigurer clients) throws Exception {

        // TODO persist clients details

        // @formatter:off
        clients.inMemory()
                .withClient("browser" )
                .authorizedGrantTypes("refresh_token" , "password" )
                .scopes("ui" )
                .accessTokenValiditySeconds(18000) // 5 hour
                .refreshTokenValiditySeconds(2592000) // 30 days
                .and()
                .withClient("account-service" )
                .secret(env.getProperty("ACCOUNT_SERVICE_PASSWORD" , "user" ))
                .authorizedGrantTypes("client_credentials" , "refresh_token" )
                .scopes("server" )
                .and()
                .withClient("sms-service" )
                .secret(env.getProperty("SMS_SERVICE_PASSWORD" , "user" ))
                .authorizedGrantTypes("client_credentials" , "refresh_token" )
                .scopes("server" )
                .and()
                .withClient("charge-service" )
                .secret(env.getProperty("CHARGE_SERVICE_PASSWORD" , "user" ))
                .authorizedGrantTypes("client_credentials" , "refresh_token" )
                .scopes("server" )
                .and()
                .withClient("delivery-service" )
                .secret(env.getProperty("DELIVERY_SERVICE_PASSWORD" , "user" ))
                .authorizedGrantTypes("client_credentials" , "refresh_token" )
                .scopes("server" )
                .and()
                .withClient("app-service" )
                .secret(env.getProperty("APP_SERVICE_PASSWORD" , "user" ))
                .authorizedGrantTypes("client_credentials" , "refresh_token" )
                .scopes("server" )
                .and()
                .withClient("monitoring-service" )
                .secret(env.getProperty("MONITORING_SERVICE_PASSWORD" , "user" ))
                .authorizedGrantTypes("client_credentials" , "refresh_token" )
                .scopes("server" )
        ;
        // @formatter:on
    }

    @Override
    public void configure(AuthorizationServerEndpointsConfigurer endpoints) throws Exception {
        endpoints
                .tokenStore(tokenStore)
                .authenticationManager(authenticationManager)
                .userDetailsService(userDetailsService);
    }

    @Override
    public void configure(AuthorizationServerSecurityConfigurer oauthServer) throws Exception {
        oauthServer
                .allowFormAuthenticationForClients()
                .tokenKeyAccess("permitAll()" )
                .checkTokenAccess("isAuthenticated()" );
    }

    /*
     * @Description : security 错误信息本地化
     * ---------------------------------
     * @Author : Liang.Guangqing
     * @Date : Create in 2018/2/5 9:09
    **/

    @Bean
    public MessageSource messageSource() {
        Locale.setDefault(Locale.SIMPLIFIED_CHINESE);
        ReloadableResourceBundleMessageSource messageSource = new ReloadableResourceBundleMessageSource();
        messageSource.addBasenames("classpath:/messages/messages" );
        return messageSource;
    }
}
```
**WebSecurityConfig**
```
@Configuration
@EnableWebSecurity
public class WebSecurityConfig extends WebSecurityConfigurerAdapter {

    @Autowired
    private SysUserDetailsService userDetailsService;

    @Override
    protected void configure(HttpSecurity http) throws Exception {
        // @formatter:off
        http
                .authorizeRequests().anyRequest().authenticated()
                .and()
                .csrf().disable();
        // @formatter:on
    }


    @Override
    protected void configure(AuthenticationManagerBuilder auth) throws Exception {
        auth
                .userDetailsService(userDetailsService)
                .passwordEncoder(new BCryptPasswordEncoder());
    }

    @Override
    @Bean
    public AuthenticationManager authenticationManagerBean() throws Exception {
        return super.authenticationManagerBean();
    }
}
```
It looks like they're the same, but the boot is wrong,
```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'resourceHandlerMapping' defined in class path resource [org/springframework/boot/autoconfigure/web/WebMvcAutoConfiguration$EnableWebMvcConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.web.servlet.HandlerMapping]: Factory method 'resourceHandlerMapping' threw exception; nested exception is java.lang.IllegalStateException: No ServletContext set
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:599) ~[spring-beans-4.3.17.RELEASE.jar:4.3.17.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1181) ~[spring-beans-4.3.17.RELEASE.jar:4.3.17.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1075) ~[spring-beans-4.3.17.RELEASE.jar:4.3.17.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:513) ~[spring-beans-4.3.17.RELEASE.jar:4.3.17.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483) ~[spring-beans-4.3.17.RELEASE.jar:4.3.17.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:312) ~[spring-beans-4.3.17.RELEASE.jar:4.3.17.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.3.17.RELEASE.jar:4.3.17.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:308) ~[spring-beans-4.3.17.RELEASE.jar:4.3.17.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) ~[spring-beans-4.3.17.RELEASE.jar:4.3.17.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:761) ~[spring-beans-4.3.17.RELEASE.jar:4.3.17.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:867) ~[spring-context-4.3.17.RELEASE.jar:4.3.17.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:543) ~[spring-context-4.3.17.RELEASE.jar:4.3.17.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122) ~[spring-boot-1.5.13.RELEASE.jar:1.5.13.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693) [spring-boot-1.5.13.RELEASE.jar:1.5.13.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360) [spring-boot-1.5.13.RELEASE.jar:1.5.13.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303) [spring-boot-1.5.13.RELEASE.jar:1.5.13.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1118) [spring-boot-1.5.13.RELEASE.jar:1.5.13.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1107) [spring-boot-1.5.13.RELEASE.jar:1.5.13.RELEASE]
	at com.lgq.auth.AuthCenterApplication.main(AuthCenterApplication.java:39) [classes/:na]
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.web.servlet.HandlerMapping]: Factory method 'resourceHandlerMapping' threw exception; nested exception is java.lang.IllegalStateException: No ServletContext set
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:189) ~[spring-beans-4.3.17.RELEASE.jar:4.3.17.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:588) ~[spring-beans-4.3.17.RELEASE.jar:4.3.17.RELEASE]
	... 18 common frames omitted
Caused by: java.lang.IllegalStateException: No ServletContext set
	at org.springframework.util.Assert.state(Assert.java:70) ~[spring-core-4.3.17.RELEASE.jar:4.3.17.RELEASE]
	at org.springframework.web.servlet.config.annotation.WebMvcConfigurationSupport.resourceHandlerMapping(WebMvcConfigurationSupport.java:448) ~[spring-webmvc-4.3.17.RELEASE.jar:4.3.17.RELEASE]
	at org.springframework.boot.autoconfigure.web.WebMvcAutoConfiguration$EnableWebMvcConfiguration$$EnhancerBySpringCGLIB$$603f4ecc.CGLIB$resourceHandlerMapping$43(<generated>) ~[spring-boot-autoconfigure-1.5.13.RELEASE.jar:1.5.13.RELEASE]
	at org.springframework.boot.autoconfigure.web.WebMvcAutoConfiguration$EnableWebMvcConfiguration$$EnhancerBySpringCGLIB$$603f4ecc$$FastClassBySpringCGLIB$$84a445b3.invoke(<generated>) ~[spring-boot-autoconfigure-1.5.13.RELEASE.jar:1.5.13.RELEASE]
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228) ~[spring-core-4.3.17.RELEASE.jar:4.3.17.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:358) ~[spring-context-4.3.17.RELEASE.jar:4.3.17.RELEASE]
	at org.springframework.boot.autoconfigure.web.WebMvcAutoConfiguration$EnableWebMvcConfiguration$$EnhancerBySpringCGLIB$$603f4ecc.resourceHandlerMapping(<generated>) ~[spring-boot-autoconfigure-1.5.13.RELEASE.jar:1.5.13.RELEASE]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_162]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_162]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_162]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_162]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162) ~[spring-beans-4.3.17.RELEASE.jar:4.3.17.RELEASE]
	... 19 common frames omitted
```
I don't know how to change it, can you tell me what's wrong? Thank you!

**Comment by Lguangqing** [comment]
It turned out that the internationalization bean was misplaced
···
@Bean
    public MessageSource messageSource() {
        Locale.setDefault(Locale.SIMPLIFIED_CHINESE);
        ReloadableResourceBundleMessageSource messageSource = new ReloadableResourceBundleMessageSource();
        messageSource.addBasenames("classpath:/messages/messages" );
        return messageSource;
    }
···
This is not in `AuthorizationServerConfigurerAdapter`

**Comment by xak2000** [comment]
I had same problem with slightly different configuration, but the root of the problem was the same: `MessageSource` bean was placed inside `WebMvcConfigurer`. After moving it into another separate `@Configuration` class - the error was gone.

This problem occured only after migration project to `spring-boot` and I think it is caused by some AutoConfiguration that somehow requires `MessageSource` bean. But if this bean is defined inside `WebMvcConfigurer` - causes too early loading of `WebMvcConfigurer` configuration, which autowires another beans etc. This leads to cylcying.
