### ISSUE TITLE
Authorization-code flow doesn't work 

### ISSUE THREAD

**Issue by nivemaham** [spring-projects/spring-security-oauth#1419]
I am getting following `BadSqlGrammarException` with following explanation when I try to execute `authorization-code` flow. 
It is strange that it says column `userid` is does not exist for a query performed as `[update oauth_approvals set expiresAt=?, status=?, lastModifiedAt=? where userId=? and clientId=? and scope=?]`
I do not understand what is the root cause of this exception since I do not see the value 'userid' anywhere in my code, database schema or query. 
I am using Postgresql as the database, if that matters and the deployment is tested on docker containers.
I have tested this on `2.2.0.RELEASE` and `2.2.1.RELEASE` versions 
I am using spring-boot as well. Tested on `1.5.2`, `1.5.9` and `1.5.11`. 
In all cases I am getting the following error.
```
managementportal-app_1         | 2018-07-03 12:06:24.282 ERROR 10 --- [  XNIO-2 task-2] o.r.m.w.rest.errors.ExceptionTranslator  : Failed to process message
managementportal-app_1         | 
managementportal-app_1         | org.springframework.jdbc.BadSqlGrammarException: PreparedStatementCallback; bad SQL grammar [update oauth_approvals set expiresAt=?, status=?, lastModifiedAt=? where userId=? and clientId=? and scope=?]; nested exception is org.postgresql.util.PSQLException: ERROR: column "userid" does not exist
managementportal-app_1         |   Hint: Perhaps you meant to reference the column "oauth_approvals.userId".
managementportal-app_1         |   Position: 77
managementportal-app_1         | 	at org.springframework.jdbc.support.SQLStateSQLExceptionTranslator.doTranslate(SQLStateSQLExceptionTranslator.java:99)
managementportal-app_1         | 	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:73)
managementportal-app_1         | 	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)
managementportal-app_1         | 	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)
managementportal-app_1         | 	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:649)
managementportal-app_1         | 	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:870)
managementportal-app_1         | 	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:931)
managementportal-app_1         | 	at org.springframework.security.oauth2.provider.approval.JdbcApprovalStore.updateApproval(JdbcApprovalStore.java:190)
managementportal-app_1         | 	at org.springframework.security.oauth2.provider.approval.JdbcApprovalStore.addApprovals(JdbcApprovalStore.java:119)
managementportal-app_1         | 	at org.springframework.security.oauth2.provider.approval.ApprovalStoreUserApprovalHandler.updateAfterApproval(ApprovalStoreUserApprovalHandler.java:223)
managementportal-app_1         | 	at org.springframework.security.oauth2.provider.endpoint.AuthorizationEndpoint.approveOrDeny(AuthorizationEndpoint.java:213)
managementportal-app_1         | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
managementportal-app_1         | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
managementportal-app_1         | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

```

It would be great if anyone could give any directions about this, since we are really blocked by this. Please
Looking forward to have some follow-up responses. Any possible lead is welcomed.

**Comment by nivemaham** [comment]
I have figured out the issues I had and solved it. The issue was specific to `PostgreSQL`, since postgresql requires to explicitly escape queries that have case-sensitive values.  
In https://github.com/spring-projects/spring-security-oauth/blob/master/spring-security-oauth2/src/main/java/org/springframework/security/oauth2/provider/approval/JdbcApprovalStore.java#L53 , there are hard-coded queries, which required to be changed.
E.g. 
```
private static final String FIELDS = "expiresAt,status,lastModifiedAt,userId,clientId,scope";
```
was replaced with
```
private static final String FIELDS = "\"expiresAt\",status,\"lastModifiedAt\",\"userId\",\"clientId\",scope";
```
It would be great if these are handled in a more generic method.
