### ISSUE TITLE
Oauth2 cannot work in JDK10 environment

### ISSUE THREAD

**Issue by zhuxiujia** [spring-projects/spring-security-oauth#1427]
Oauth2 cannot work in JDK10 environment，Spring5,Srpingboot 2.0.1,Spring Cloud Finchley.RELEASE,
There is  hint to quit, however disabling spring security and oauth2 will work.
---------------------------------------this is the code--------------------------------

Caused by: java.lang.ClassNotFoundException: com.sun.xml.internal.bind.v2.ContextFactory
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582) ~[na:na]
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:190) ~[na:na]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499) ~[na:na]
	at javax.xml.bind.ServiceLoaderUtil.nullSafeLoadClass(ServiceLoaderUtil.java:122) ~[jaxb-api-2.3.0.jar:2.3.0]
	at javax.xml.bind.ServiceLoaderUtil.safeLoadClass(ServiceLoaderUtil.java:155) ~[jaxb-api-2.3.0.jar:2.3.0]
	at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:276) ~[jaxb-api-2.3.0.jar:2.3.0]

**Comment by Json4** [comment]
gradle 添加下面几个依赖

```
compile "javax.activation:activation"
compile "javax.xml.bind:jaxb-api"
compile "com.sun.xml.bind:jaxb-core:${jaxbVersion}"
compile "com.sun.xml.bind:jaxb-impl:${jaxbVersion}"
```

maven对应的去找找
