### ISSUE TITLE
Oauth2 error after upgrading to spring boot 2.0.2

### ISSUE THREAD

**Issue by viplavfauzdar** [spring-projects/spring-security-oauth#1517]
Hello, I upgraded to spring boot 2.0.2 from 1.15.15 and started getting the below exception even though it did found the user. 
 
Dependency:
compile 'org.springframework.boot:spring-boot-starter-security'
compile 'org.springframework.security.oauth.boot:spring-security-oauth2-autoconfigure:2.1.0.RELEASE'

Stacktrace:
org.springframework.security.core.userdetails.UsernameNotFoundException: QAT1093
at org.springframework.security.provisioning.InMemoryUserDetailsManager.loadUserByUsername(InMemoryUserDetailsManager.java:146) ~[spring-security-core-5.0.5.RELEASE.jar:5.0.5.RELEASE]
at org.springframework.security.oauth2.provider.token.DefaultUserAuthenticationConverter.extractAuthentication(DefaultUserAuthenticationConverter.java:76) ~[spring-security-oauth2-2.3.4.RELEASE.jar:na]
at

**Comment by viplavfauzdar** [comment]
Below is my resource server config. This works with spring-boot v1.5.15 and spring-security-oauth2 v2.3.4 as expected but breaks with boot v2.0.2

@configuration
@EnableResourceServer
public class ResourceConfig extends ResourceServerConfigurerAdapter{

public void configure(ResourceServerSecurityConfigurer resources) throws Exception {
    resources.resourceId(null);  	      
}				

public void configure(HttpSecurity http) throws Exception {
	http
	.authorizeRequests()		
		.antMatchers("/index.html").permitAll()
		.antMatchers("/gettoken").permitAll()
		.antMatchers("/api/**").authenticated();
	
	http.csrf().disable();
	http.logout().invalidateHttpSession(true);
}
}

**Comment by viplavfauzdar** [comment]
And here is my application.properties entries

security.oauth2.client.access-token-uri = https://auth.login.run-np.homedepot.com/oauth/token
security.oauth2.resource.jwt.key-uri = https://auth.login.run-np.homedepot.com/token_key
security.oauth2.resource.user-info-uri = https://auth.login.run-np.homedepot.com/userinfo
security.oauth2.resource.token-info-uri = https://auth.login.run-np.homedepot.com/token_key
security.oauth2.resource.token-type=Bearer

**Comment by viplavfauzdar** [comment]
Anything on this?

**Comment by divyang001** [comment]
Hey @viplavfauzdar  were you able to resolve this ? I am also facing this issue
