### ISSUE TITLE
Improve handling of invalid tokens

### ISSUE THREAD

**Issue by ertwroc** [spring-projects/spring-security-oauth#1522]
When I try to authenticate using invalid Bearer token (e.g. by removing last character from the token) I get Internal Server Error 500 instead of Unauthorized 401 as the result of following exception:

```
2018-11-05 13:58:01.345  INFO 14792 --- [on(6)-127.0.0.1] o.s.web.servlet.DispatcherServlet        : FrameworkServlet 'dispatcherServlet': initialization completed in 23 ms
java.lang.RuntimeException: java.security.SignatureException: Signature length not correct: got 257 but was expecting 256
               at org.springframework.security.jwt.crypto.sign.RsaVerifier.verify(RsaVerifier.java:59)
               at org.springframework.security.jwt.JwtImpl.verifySignature(JwtHelper.java:287)
               at org.springframework.security.oauth2.provider.token.store.jwk.JwkVerifyingJwtAccessTokenConverter.decode(JwkVerifyingJwtAccessTokenConverter.java:122)
               at org.springframework.security.oauth2.provider.token.store.JwtTokenStore.convertAccessToken(JwtTokenStore.java:88)
               at org.springframework.security.oauth2.provider.token.store.JwtTokenStore.readAccessToken(JwtTokenStore.java:80)
               at org.springframework.security.oauth2.provider.token.store.jwk.JwkTokenStore.readAccessToken(JwkTokenStore.java:212)
               at org.springframework.security.oauth2.provider.token.DefaultTokenServices.loadAuthentication(DefaultTokenServices.java:229)
               at org.springframework.security.oauth2.provider.authentication.OAuth2AuthenticationManager.authenticate(OAuth2AuthenticationManager.java:83)
               at org.springframework.security.oauth2.provider.authentication.OAuth2AuthenticationProcessingFilter.doFilter(OAuth2AuthenticationProcessingFilter.java:150)
               at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
               at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116)
               at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
               at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:66)
               at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
               at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
               at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
               at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
               at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56)
               at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
               at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
               at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:215)
               at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:178)
               at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:357)
               at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:270)
               at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
               at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
               at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
               at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
               at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
               at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
               at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:109)
               at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
               at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
               at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
               at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:93)
               at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
               at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
               at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
               at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200)
               at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
               at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
               at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
               at io.opentracing.contrib.web.servlet.filter.TracingFilter.doFilter(TracingFilter.java:165)
               at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
               at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
               at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
               at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
               at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:496)
               at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
               at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
               at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
               at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
               at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803)
               at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
               at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:790)
               at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1468)
               at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
               at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
               at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
               at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
               at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: java.security.SignatureException: Signature length not correct: got 257 but was expecting 256
               at java.base/sun.security.rsa.RSASignature.engineVerify(RSASignature.java:191)
               at java.base/java.security.Signature$Delegate.engineVerify(Signature.java:1245)
               at java.base/java.security.Signature.verify(Signature.java:674)
               at org.springframework.security.jwt.crypto.sign.RsaVerifier.verify(RsaVerifier.java:54)
               ... 60 more
```

It could be improved eg. by catching RuntimeExceptions in `JwtTokenStore.readAccessToken` and wrapping them in `InvalidTokenException`

**Comment by guykoth** [comment]
We are having the same issue.
Did anyone look at this issue by any chance?

**Comment by MRDcoder** [comment]
Hi,

Any update on this issue ?

**Comment by jgrandja** [comment]
Thank you for the report @ertwroc. I applied your suggestion and just pushed the update to master.

**Comment by MRDcoder** [comment]
@jgrandja Hello , can you please let me know when this fix will be available on maven ? Last time, i checked it was with 2.4.1 version and release data was 21st april.

**Comment by jgrandja** [comment]
@MRDcoder It's in central now.

**Comment by MRDcoder** [comment]
Hi Joe ,
thank you for replying but i am not able to see in central. If you don't mind can you share the link here?

**Comment by jgrandja** [comment]
Here it is https://repo1.maven.org/maven2/org/springframework/security/oauth/spring-security-oauth2/
