### ISSUE TITLE
Not allowed to deserialize java.time.Ser

### ISSUE THREAD

**Issue by OrangeDog** [spring-projects/spring-security-oauth#1803]
### Summary

After upgrading from 2.3.6 to 2.3.7 with no other dependency changes, the `JdkSerializationStrategy` cannot read authentication objects (including those it writes), though it can still write them.

### Actual Behavior

```
org.springframework.core.serializer.support.SerializationFailedException: Failed to deserialize payload; nested exception is java.io.NotSerializableException: Not allowed to deserialize java.time.Ser
	at org.springframework.security.oauth2.provider.token.store.redis.JdkSerializationStrategy.deserializeInternal(JdkSerializationStrategy.java:64)
	at org.springframework.security.oauth2.provider.token.store.redis.BaseRedisTokenStoreSerializationStrategy.deserialize(BaseRedisTokenStoreSerializationStrategy.java:21)
	at com.myapp.PatchedRedisTokenStore.deserializeAuthentication(PatchedRedisTokenStore.java:92)
	at com.myapp.PatchedRedisTokenStore.readAuthentication(PatchedRedisTokenStore.java:146)
	at com.myapp.PatchedRedisTokenStore.readAuthentication(PatchedRedisTokenStore.java:134)
	at com.myapp.PatchedRedisTokenStore$$FastClassBySpringCGLIB$$ed1074ee.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:769)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:88)
	at com.myapp.AuthenticationInterceptor.wrap(AuthenticationInterceptor.java:20)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:644)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:633)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:93)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689)
	at com.myapp.ExtendedRedisTokenStore$$EnhancerBySpringCGLIB$$502e757.readAuthentication(<generated>)
	at com.myapp.OAuthManageController.manageTokens(OAuthManageController.java:76)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:888)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:793)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	... 88 common frames omitted
Caused by: java.io.NotSerializableException: Not allowed to deserialize java.time.Ser
	at org.springframework.security.oauth2.provider.token.store.redis.SaferObjectInputStream.resolveClass(SaferObjectInputStream.java:59)
	at java.base/java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1886)
	at java.base/java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1772)
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2060)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1594)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:430)
	at java.base/java.util.HashMap.readObject(HashMap.java:1460)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.base/java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1160)
	at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2216)
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2087)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1594)
	at java.base/java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2355)
	at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2249)
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2087)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1594)
	at java.base/java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2355)
	at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2249)
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2087)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1594)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:430)
	at org.springframework.security.oauth2.provider.token.store.redis.JdkSerializationStrategy.deserializeInternal(JdkSerializationStrategy.java:62)
	... 127 common frames omitted
```

### Expected Behavior

No failure.

### Configuration

```java
endpoints
    .approvalStoreDisabled()
    .reuseRefreshTokens(false)
    .requestValidator(new RequestValidator())  // workaround for #1671
    .userDetailsService(userDetailsService)  //  a basic JPA-backed service
    .tokenStore(oauthTokenStore())  // new ExtendedRedisTokenStore(redisConnectionFactory) 
    .authorizationCodeServices(new InMemoryAuthorizationCodeServices())
;
```

### Version

Only occurs in 2.3.7.RELEASE

### Sample

For my classes in the stack trace, which should all be irrelevant:

- `PatchedRedisTokenStore` is the changes from #1660
- `ExtendedRedisTokenStore` adds lookups `ByUserName` in addition to `ByClientIdAndUserName`

```java
@Aspect
public class AuthenticationInterceptor {

    @Pointcut("within(org.springframework.security.oauth2.provider.token.TokenStore+)")
    private void withinTokenStore() {}

    @Pointcut("execution(public org.springframework.security.oauth2.provider.OAuth2Authentication *(..))")
    private void returningAuthentication() {}

    @Around("withinTokenStore() && returningAuthentication()")
    public OAuth2Authentication wrap(ProceedingJoinPoint pjp) throws Throwable {
        return new OAuth2AuthenticationWrapper((OAuth2Authentication) pjp.proceed());
    }
}
```
```java
public class OAuth2AuthenticationWrapper extends OAuth2Authentication {
    private final Collection<GrantedAuthority> authorities;

    OAuth2AuthenticationWrapper(OAuth2Authentication delegate) {
        super(delegate.getOAuth2Request(), delegate.getUserAuthentication());
        Set<String> scopes = delegate.getOAuth2Request().getScope();
        authorities = delegate.getAuthorities().stream()
                .filter(a -> scopes.contains(a.getAuthority().replace("ROLE_", "")))
                .collect(Collectors.toUnmodifiableSet());
    }

    @Override
    public Collection<GrantedAuthority> getAuthorities() {
        return this.authorities;
    }
}
```

**Comment by OrangeDog** [comment]
I'm guessing this was caused by #1682

**Comment by jgrandja** [comment]
@OrangeDog This has been addressed in #1785. Closing as duplicate. FYI, 2.3.8 is being released this Thur Nov 14.

**Comment by OrangeDog** [comment]
@jgrandja any reason this class (or the `java.time` package) isn't on the default whitelist?

**Comment by jgrandja** [comment]
@OrangeDog The default `SerializationStrategy` (`DefaultSerializationStrategy`) allows all classes. If you want to configure stricter serialization, you'll need to configure `WhitelistedSerializationStrategy` with the allowed classes and set that via `SerializationUtils.setSerializationStrategy()` or using `META-INF/spring.factories`. See the javadoc for `SerializationUtils`. This addition will be in 2.4.x only.
