### ISSUE TITLE
Client application request error

### ISSUE THREAD

**Issue by dbclkclk** [spring-projects/spring-security-oauth#340]
I am getting this issue when try to issue a request to an endpoint. I am using the `client_credentials` grant type. 

```
 Dec 17, 2014 2:01:08 PM org.apache.catalina.core.StandardWrapperValve invoke
 SEVERE: Servlet.service() for servlet [spring] in context with path [] threw exception [Request  processing failed; nested exception is error="access_denied", error_description="Error requesting access token."] with root cause
  org.springframework.web.client.HttpServerErrorException: 500 Incorrect result size: expected 1, actual 2
at     org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:91)
at org.springframework.security.oauth2.client.token.OAuth2AccessTokenSupport$AccessTokenErrorHandler.handleError(OAuth2AccessTokenSupport.java:243)
at org.springframework.web.client.RestTemplate.handleResponseError(RestTemplate.java:556)
at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:514)
at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:479)
at org.springframework.security.oauth2.client.token.OAuth2AccessTokenSupport.retrieveToken(OAuth2AccessTokenSupport.java:136)
at org.springframework.security.oauth2.client.token.grant.client.ClientCredentialsAccessTokenProvider.obtainAccessToken(ClientCredentialsAccessTokenProvider.java:44)
at org.springframework.security.oauth2.client.token.AccessTokenProviderChain.obtainNewAccessTokenInternal(AccessTokenProviderChain.java:142)
at org.springframework.security.oauth2.client.token.AccessTokenProviderChain.obtainAccessToken(AccessTokenProviderChain.java:118)
at org.springframework.security.oauth2.client.OAuth2RestTemplate.acquireAccessToken(OAuth2RestTemplate.java:221)
at org.springframework.security.oauth2.client.OAuth2RestTemplate.getAccessToken(OAuth2RestTemplate.java:173)
at org.springframework.security.oauth2.client.OAuth2RestTemplate.createRequest(OAuth2RestTemplate.java:105)
at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:505)
at org.springframework.security.oauth2.client.OAuth2RestTemplate.doExecute(OAuth2RestTemplate.java:128)
at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:485)
at org.springframework.web.client.RestTemplate.getForEntity(RestTemplate.java:276)
at com.xxxxxxx.site.controllers.LoginController.verifyCredential(LoginController.java:63)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:483)
at org.springframework.web.method.support.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:215)
at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:132)
at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:104)
at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandleMethod(RequestMappingHandlerAdapter.java:745)
at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:686)
at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:80)
at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:925)
at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:856)
at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:953)
at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:855)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:646)
at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:829)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:503)
at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:421)
at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1070)
at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:611)
at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.doRun(AprEndpoint.java:2466)
at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.run(AprEndpoint.java:2455)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
at java.lang.Thread.run(Thread.java:745)
```

My configuration is this however, I do not have a tokenStore:

```
    <oauth:client id="oauth2ClientFilter" />

<!--define an oauth 2 resource for sparklr -->
<oauth:resource id="clientCredentialsResource" type="client_credentials" client-authentication-scheme="header"  client-id="xxxxxxx"  client-secret="xxxxxx"
    access-token-uri="${oauth.accessTokenUri}" />

<bean id="twoFactorAuth" class="com.xxxxxx.site.overrides.TokenOauthResourceDetails">
    <property name="grantType" value="two_factor"></property>
    <property name="clientAuthenticationScheme" value="header"></property>
    <property name="clientId" value="xxxxxx"></property>
    <property name="clientSecret" value="p@ssw0rd"></property>
    <property name="accessTokenUri" value="${oauth.accessTokenUri}"></property>
</bean>

<bean id="cPassword" class="org.springframework.security.oauth2.client.token.grant.password.ResourceOwnerPasswordResourceDetails">
    <property name="grantType" value="c_password"></property>
    <property name="clientAuthenticationScheme" value="header"></property>
    <property name="clientId" value="xxxxxxx"></property>
    <property name="clientSecret" value="xxxxxxx"></property>
    <property name="accessTokenUri" value="${oauth.accessTokenUri}"></property>
</bean>

<context:property-placeholder location="classpath:/META-INF/properties/local.properties" />

  <mvc:default-servlet-handler />

<oauth:rest-template id="cPasswordRest" resource="cPassword" access-token-provider="accessTokenProvider">
</oauth:rest-template>

<oauth:rest-template id="voteRestTemplate" resource="clientCredentialsResource" access-token-provider="accessTokenProvider">
</oauth:rest-template>


<bean class="org.springframework.security.oauth2.client.token.AccessTokenProviderChain" id="accessTokenProvider">
    <constructor-arg>
        <list>
            <bean class="org.springframework.security.oauth2.client.token.grant.client.ClientCredentialsAccessTokenProvider"/>
            <bean class="com.xxxxxxx.site.overrides.CustomResourceOwnerPasswordProviderToken"/>
            <bean class="com.xxxxxx.site.overrides.TokenOauthAccessProvider" />
        </list>
    </constructor-arg>
</bean>
```

On my server I am seeing these logs:

```
 014-12-17 19:17:58.896:WARN::/oauth/token
 2014-12-17T19:17:58.898620+00:00 app[web.1]:    org.springframework.dao.IncorrectResultSizeDataAccessException: Incorrect result size: expected 1, actual 2
 2014-12-17T19:17:58.898622+00:00 app[web.1]:   at  org.springframework.dao.support.DataAccessUtils.requiredSingleResult(DataAccessUtils.java:74)
 2014-12-17T19:17:58.898623+00:00 app[web.1]:   at  org.springframework.jdbc.core.JdbcTemplate.queryForObject(JdbcTemplate.java:737)
 2014-12-17T19:17:58.898625+00:00 app[web.1]:   at org.springframework.security.oauth2.provider.token.JdbcTokenStore.getAccessToken(JdbcTokenStore.java:105)
 2014-12-17T19:17:58.898626+00:00 app[web.1]:   at or g.springframework.security.oauth2.provider.token.DefaultTokenServices.createAccessToken(DefaultTokenServices.java:75)
 2014-12-17T19:17:58.898627+00:00 app[web.1]:   at org.springframework.security.oauth2.provider.token.AbstractTokenGranter.getAccessToken(AbstractTokenGranter.java:68)
 2014-12-17T19:17:58.898629+00:00 app[web.1]:   at org.springframework.security.oauth2.provider.token.AbstractTokenGranter.grant(AbstractTokenGranter.java:60)
 2014-12-17T19:17:58.898630+00:00 app[web.1]:   at org.springframework.security.oauth2.provider.client.ClientCredentialsTokenGranter.grant(ClientCredentialsTokenGranter.java:41)
  2014-12-17T19:17:58.898631+00:00 app[web.1]:  at org.springframework.security.oauth2.provider.CompositeTokenGranter.grant(CompositeTokenGranter.java:38)
 2014-12-17T19:17:58.898633+00:00 app[web.1]:   at org.springframework.security.oauth2.provider.endpoint.TokenEndpoint.getAccessToken(TokenEndpoint.java:100)
 2014-12-17T19:17:58.898634+00:00 app[web.1]:   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 2014-12-17T19:17:58.898635+00:00 app[web.1]:   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
 2014-12-17T19:17:58.898637+00:00 app[web.1]:   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 2014-12-17T19:17:58.898638+00:00 app[web.1]:   at java.lang.reflect.Method.invoke(Method.java:606)
 2014-12-17T19:17:58.898640+00:00 app[web.1]:   at org.springframework.web.method.support.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:215)
  2014-12-17T19:17:58.898642+00:00 app[web.1]:  at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:132)
 2014-12-17T19:17:58.898643+00:00 app[web.1]:   at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:104)
 2014-12-17T19:17:58.898645+00:00 app[web.1]:   at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandleMethod(RequestMappingHandlerAdapter.java:745)
 2014-12-17T19:17:58.898646+00:00 app[web.1]:   at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:686)
 2014-12-17T19:17:58.898647+00:00 app[web.1]:   at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:80)
  2014-12-17T19:17:58.898649+00:00 app[web.1]:  at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:925)
  2014-12-17T19:17:58.898650+00:00 app[web.1]:  at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:856)
 2014-12-17T19:17:58.898651+00:00
```

**Comment by joemccall86** [comment]
@jonasflesch I'm currently faced with the same issue. So I understand, does creating the unique constraint on the authentication_id column prevent the row from being inserted, or would it cause a non-unique exception to be thrown upon token creation (assuming competing threads are trying to create tokens with the same authentication id)?

**Comment by jonasflesch** [comment]
After 6 months of production usage we never faced non-unique exceptions. But we also updated to the 2.0.5-RELEASE version, which fixed a bug related to it.

**Comment by JavaHelper** [comment]
@jonasflesch - could you please guide here: https://stackoverflow.com/questions/53989458/org-springframework-security-oauth2-common-exceptions-invalidgrantexception-bad ?
