### ISSUE TITLE
HTTP 401 when getting photos in sparklr2 sample application

### ISSUE THREAD

**Issue by ShardPhoenix** [spring-projects/spring-security-oauth#380]
I've been trying out the oauth2 sample apps. Everything is working fine for the most part - I can use Tonr to retrieve and display the photos for user marissa via oauth login to sparklr2. However, on sparklr2 itself, I can't see any photos even after logging in, with an error "http://localhost:8080/sparklr2/photos  [HTTP/1.1 401 Unauthorized 2ms]" in the browser console on /index.jsp. I also get a 401 if I try to go directly to /photos, with this xml error:

    <oauth>
    <error_description>
    An Authentication object was not found in the SecurityContext
    </error_description>
    <error>unauthorized</error>
    </oauth>

Same happens for user paul. Any idea what's going on?

Here is part of the logs from around the error:

```
sparklr2 10:30:08.671 [DEBUG] FilterChainProxy - /photos?callback=pictureDisplay&format=json at position 4 of 10 in additional filter chain; firing Filter: 'LogoutFilter'
sparklr2 10:30:08.671 [DEBUG] AntPathRequestMatcher - Checking match of request : '/photos'; against '/logout'
sparklr2 10:30:08.671 [DEBUG] FilterChainProxy - /photos?callback=pictureDisplay&format=json at position 5 of 10 in additional filter chain; firing Filter: 'OAuth2AuthenticationProcessingFilter'
sparklr2 10:30:08.671 [DEBUG] BearerTokenExtractor - Token not found in headers. Trying request parameters.
sparklr2 10:30:08.671 [DEBUG] BearerTokenExtractor - Token not found in request parameters.  Not an OAuth2 request.
sparklr2 10:30:08.671 [DEBUG] OAuth2AuthenticationProcessingFilter - No token in request, will continue chain.
sparklr2 10:30:08.671 [DEBUG] FilterChainProxy - /photos?callback=pictureDisplay&format=json at position 6 of 10 in additional filter chain; firing Filter: 'RequestCacheAwareFilter'
sparklr2 10:30:08.671 [DEBUG] FilterChainProxy - /photos?callback=pictureDisplay&format=json at position 7 of 10 in additional filter chain; firing Filter: 'SecurityContextHolderAwareRequestFilter'
sparklr2 10:30:08.671 [DEBUG] FilterChainProxy - /photos?callback=pictureDisplay&format=json at position 8 of 10 in additional filter chain; firing Filter: 'SessionManagementFilter'
sparklr2 10:30:08.671 [DEBUG] FilterChainProxy - /photos?callback=pictureDisplay&format=json at position 9 of 10 in additional filter chain; firing Filter: 'ExceptionTranslationFilter'
sparklr2 10:30:08.671 [DEBUG] FilterChainProxy - /photos?callback=pictureDisplay&format=json at position 10 of 10 in additional filter chain; firing Filter: 'FilterSecurityInterceptor'
sparklr2 10:30:08.672 [DEBUG] AntPathRequestMatcher - Checking match of request : '/photos'; against '/me'
sparklr2 10:30:08.672 [DEBUG] AntPathRequestMatcher - Checking match of request : '/photos'; against '/photos'
sparklr2 10:30:08.672 [DEBUG] FilterSecurityInterceptor - Secure object: FilterInvocation: URL: /photos?callback=pictureDisplay&format=json; Attributes: [#oauth2.throwOnError(#oauth2.hasScope('read') or (!#oauth2.isOAuth() and hasRole('ROLE_USER')))]
sparklr2 10:30:08.672 [DEBUG] ExceptionTranslationFilter - Authentication exception occurred; redirecting to authentication entry point <org.springframework.security.authentication.AuthenticationCredentialsNotFoundException: An Authentication object was not found in the SecurityContext>org.springframework.security.authentication.AuthenticationCredentialsNotFoundException: An Authentication object was not found in the SecurityContext
	at org.springframework.security.access.intercept.AbstractSecurityInterceptor.credentialsNotFound(AbstractSecurityInterceptor.java:339)
	at org.springframework.security.access.intercept.AbstractSecurityInterceptor.beforeInvocation(AbstractSecurityInterceptor.java:198)
```

**Comment by dsyer** [comment]
Fixed in commit 3c18f07. Thanks.
