### ISSUE TITLE
BeanCreationException

### ISSUE THREAD

**Issue by roybrener** [spring-projects/spring-security-oauth#382]
My `SpringOauthConf` file:

```
    @Configuration
    public class Oauth2ServerConfiguration {
        public static final String RESOURCE_ID = "resource";

    /**
     * Created by roy on 5/25/2014.
     * this is the security configuration class
     */
    @Configuration
    @EnableWebMvcSecurity
    public class SecurityConfiguration extends WebSecurityConfigurerAdapter {

        @Autowired
        UserService userService;

        @Override
        protected void configure(AuthenticationManagerBuilder builder) throws Exception {
            builder.userDetailsService(userService)
                   .passwordEncoder(new BCryptPasswordEncoder());
        }

        @Override
        public void configure(WebSecurity security) throws Exception {
            security.ignoring().antMatchers("/resource/**");
        }

        @Override
        @Bean
        public AuthenticationManager authenticationManagerBean() throws Exception {
            return super.authenticationManagerBean();
        }

        @Override
        protected void configure(HttpSecurity security) throws Exception {
            security.authorizeRequests()
                    .antMatchers("/signup", "about", "policies").permitAll()
                    .antMatchers("/secure/**").hasAnyAuthority("USER")
                    .antMatchers("/admin/**").hasAnyAuthority("ADMIN")
                    .anyRequest().authenticated()
                    .and().formLogin()
                    .loginPage("/loginA").failureUrl("/loginA?error")
                    .defaultSuccessUrl("/secure")
                    .usernameParameter("email")
                    .passwordParameter("password")
                    .permitAll()
                    .and().logout()
                    .logoutUrl("/logout")
                    .logoutSuccessUrl("/login?loggedOut")
                    .invalidateHttpSession(true).deleteCookies("JSESSIONID")
                    .permitAll()
                    .and().sessionManagement().sessionFixation().changeSessionId().maximumSessions(4).maxSessionsPreventsLogin(true)
                    .and().and().csrf().disable();
        }
    }


    @Configuration
    @EnableResourceServer
    protected static class ResourceServerConfiguration extends ResourceServerConfigurerAdapter{

        @Override
        public void configure (ResourceServerSecurityConfigurer resources) throws Exception {
            resources.resourceId(RESOURCE_ID);
        }

        @Override
        public void configure (HttpSecurity http) throws Exception {
            http.authorizeRequests().anyRequest().access("#oauth2.hasScope('read')");
        }
    }

    @Configuration
    @EnableAuthorizationServer
    protected static class AuthorizationServerConfig extends AuthorizationServerConfigurerAdapter{

        @Autowired
        DefaultUserService userService;

        @Autowired
        TokenStore tokenStore;

        @Autowired
        @Qualifier("authenticationManagerBean")
        private AuthenticationManager authenticationManager;

//        @Bean
//        public AuthenticationManager authenticationManager(){
//            final OAuth2AuthenticationManager oAuth2AuthenticationManager = new OAuth2AuthenticationManager();
//            oAuth2AuthenticationManager.setClientDetailsService(userService);
//            oAuth2AuthenticationManager.setTokenServices(new DefaultTokenServices());
//            oAuth2AuthenticationManager.setResourceId(RESOURCE_ID);
//
//            return oAuth2AuthenticationManager;
//        }

        @Override
        public void configure (AuthorizationServerSecurityConfigurer security) throws Exception {
            security.realm("client/q");
        }

        @Override
        public void configure (ClientDetailsServiceConfigurer clients) throws Exception {
            clients.withClientDetails(userService);

        }

        @Override
        public void configure (AuthorizationServerEndpointsConfigurer endpoints) throws Exception {
            endpoints.tokenStore(tokenStore).authenticationManager(authenticationManager);
        }

        @Bean public TokenStore tokenStore(){
            return new InMemoryTokenStore();
        }
    }
}
```

Exception that i'm getting: 

```
     org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.security.oauth2.config.annotation.web.configuration.AuthorizationServerEndpointsConfiguration': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private java.util.List org.springframework.security.oauth2.config.annotation.web.configuration.AuthorizationServerEndpointsConfiguration.configurers; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'com.example.config.Oauth2ServerConfiguration$AuthorizationServerConfig': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.springframework.security.authentication.AuthenticationManager com.example.config.Oauth2ServerConfiguration$AuthorizationServerConfig.authenticationManager; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'com.example.config.Oauth2ServerConfiguration$SecurityConfiguration': Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.example.config.Oauth2ServerConfiguration$SecurityConfiguration$$EnhancerBySpringCGLIB$$1338ebc7]: No default constructor found; nested exception is java.lang.NoSuchMethodException: com.example.config.Oauth2ServerConfiguration$SecurityConfiguration$$EnhancerBySpringCGLIB$$1338ebc7.<init>()
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:334) ~[AutowiredAnnotationBeanPostProcessor.class:4.1.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1202) ~[AbstractAutowireCapableBeanFactory.class:4.1.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:537) ~[AbstractAutowireCapableBeanFactory.class:4.1.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:476) ~[AbstractAutowireCapableBeanFactory.class:4.1.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:303) ~[AbstractBeanFactory$1.class:4.1.4.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[DefaultSingletonBeanRegistry.class:4.1.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:299) ~[AbstractBeanFactory.class:4.1.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194) ~[AbstractBeanFactory.class:4.1.4.RELEASE]

    Caused by: org.springframework.beans.factory.BeanCreationException: Could not autowire field: private java.util.List org.springframework.security.oauth2.config.annotation.web.configuration.AuthorizationServerEndpointsConfiguration.configurers; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'com.example.config.Oauth2ServerConfiguration$AuthorizationServerConfig': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.springframework.security.authentication.AuthenticationManager com.example.config.Oauth2ServerConfiguration$AuthorizationServerConfig.authenticationManager; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'com.example.config.Oauth2ServerConfiguration$SecurityConfiguration': Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.example.config.Oauth2ServerConfiguration$SecurityConfiguration$$EnhancerBySpringCGLIB$$1338ebc7]: No default constructor found; nested exception is java.lang.NoSuchMethodException: com.example.config.Oauth2ServerConfiguration$SecurityConfiguration$$EnhancerBySpringCGLIB$$1338ebc7.<init>()
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:561) ~[AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.class:4.1.4.RELEASE]
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88) ~[InjectionMetadata.class:4.1.4.RELEASE]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:331) ~[AutowiredAnnotationBeanPostProcessor.class:4.1.4.RELEASE] 

    Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'com.example.config.Oauth2ServerConfiguration$AuthorizationServerConfig': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.springframework.security.authentication.AuthenticationManager com.example.config.Oauth2ServerConfiguration$AuthorizationServerConfig.authenticationManager; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'com.example.config.Oauth2ServerConfiguration$SecurityConfiguration': Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.example.config.Oauth2ServerConfiguration$SecurityConfiguration$$EnhancerBySpringCGLIB$$1338ebc7]: No default constructor found; nested exception is java.lang.NoSuchMethodException: com.example.config.Oauth2ServerConfiguration$SecurityConfiguration$$EnhancerBySpringCGLIB$$1338ebc7.<init>()
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:334) ~[AutowiredAnnotationBeanPostProcessor.class:4.1.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1202) ~[AbstractAutowireCapableBeanFactory.class:4.1.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:537) ~[AbstractAutowireCapableBeanFactory.class:4.1.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:476) ~[AbstractAutowireCapableBeanFactory.class:4.1.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:303) ~[AbstractBeanFactory$1.class:4.1.4.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[DefaultSingletonBeanRegistry.class:4.1.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:299) ~[AbstractBeanFactory.class:4.1.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194) ~[AbstractBeanFactory.class:4.1.4.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:1127) ~[DefaultListableBeanFactory.class:4.1.4.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1003) ~[DefaultListableBeanFactory.class:4.1.4.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:949) ~[DefaultListableBeanFactory.class:4.1.4.RELEASE]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:533) ~[AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.class:4.1.4.RELEASE]
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88) ~[InjectionMetadata.class:4.1.4.RELEASE]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:331) ~[AutowiredAnnotationBeanPostProcessor.class:4.1.4.RELEASE]
	... 56 more
```

I'm guessing it's a configuration problem on my end. please help solving this issue.

**Comment by dsyer** [comment]
Is that `SecurityConfiguration` really supposed to be an inner class? If so it has to be "static".

**Comment by roybrener** [comment]
ohh, i'm sorry to not pointing it out...the class is not an inner class. it's a class of it's own...i've just copied it to show all the code

**Comment by dsyer** [comment]
Second stupid question: if `SecurityConfiguration` actually part of the application context?

**Comment by roybrener** [comment]
I'm using SecurityBootstarp and MethodSecurtyConfig: 

    @SuppressWarnings("unused")
    @Order(2)
   public class SecurityBootstrap extends AbstractSecurityWebApplicationInitializer
   {
        private static final Logger log = LogManager.getLogger();

        @Override
        protected boolean enableHttpSessionEventPublisher()
        {
            log.info("Executing security bootstrap.");

            return true;
        }
}

Is it possible maybe to attach / send you a sample code of my configuration, maybe it will be clearer. the code that i'm using is almost identical to the sparklr app but the `ServletInitializer`

    @Order(1)
    public class FrameworkBootstrap implements WebApplicationInitializer {
        private static final Logger log = LogManager.getLogger();

        @Override
        public void onStartup (ServletContext container) throws ServletException {
            log.info("Executing framework bootstrap.");

            container.getServletRegistration("default").addMapping("/resource/*");

            AnnotationConfigWebApplicationContext rootContext =
                new AnnotationConfigWebApplicationContext();
            rootContext.register(RootContextConfiguration.class);
            container.addListener(new ContextLoaderListener(rootContext));

            AnnotationConfigWebApplicationContext restContext =
                new AnnotationConfigWebApplicationContext();
            restContext.register(RestServletConfiguration.class);
            DispatcherServlet restServlet = new DispatcherServlet(restContext);
            restServlet.setDispatchOptionsRequest(true);
            ServletRegistration.Dynamic dispatcher = container.addServlet("springRestDispatcher", restServlet);
            dispatcher.setLoadOnStartup(1);
            dispatcher.addMapping("/rest/*");

            DelegatingFilterProxy filter = new DelegatingFilterProxy("springSecurityFilterChain");
            filter.setServletContext(restServlet.getServletContext());
            container.addFilter("springSecurityFilterChain", filter).addMappingForUrlPatterns(null, false, "/*");

    }
}

**Comment by roybrener** [comment]
i've changed the `SecurityConfiguration` Annotation to `@EnableWebMvcSecurity` from `@EnableWebSecurity'. now the exception that i'm getting is different. same as https://github.com/spring-projects/spring-boot/issues/568. is there a valid solution? Thanks again!

**Comment by dsyer** [comment]
That's a Spring Boot issue and your app isn't a Spring Boot app from what I have seen. Maybe you could push the code to github and paste a link?

**Comment by roybrener** [comment]
Thanks for your help, i've managed to solve the problem (-:.

**Comment by zhorkay** [comment]
Hi Roy, I'm using the same code, a sample project from "Wrox Professional Java for Web Applications" and I have exactly the same error. What was your solution?
