### ISSUE TITLE
Password Grant Type issue: JdbcClientDetailsService error. 

### ISSUE THREAD

**Issue by deanclkclk** [spring-projects/spring-security-oauth#414]
I am currently getting this error:

     org.springframework.dao.EmptyResultDataAccessException: Incorrect result size: expected 1, actual 0

Which is handled by the `DaoAuthenticationProvider` however, it throws an `InternalAuthenticationServiceException` exception. This bypasses the exception handling of the `ProviderManager`, which does not call my customDaoProvider which would authenticate the resource owner. 

Note this happens when it tries to authenticate the Resource Owner and not the Client (Client was already authenticated from a previous roundtrip; I guess this is how it should work based on Spring-Oauth). Could you explain why this error is throw? Thanks.

**Comment by dsyer** [comment]
That looks like a question for Spring Security not for OAuth? If you have a custom provider, don't you need to remove the default `DaoAuthenticationProvider` (if that's the one that is broken)?

**Comment by deanclkclk** [comment]
@dsyer Yes I provided a custom `DaoAuthenticationProvider` (which is the customDaoProvider I eluded to earlier) for my custom grant type. The thing is, it seem how Spring Security works is that it uses the ProviderManager to  cycle through a bunch of `DaoAutheticationProvider` (which includes for both client and user authentication) until one verifies the user. 

My observation is that on the first iteration of the ProviderManager, it selects DefaultDaoAuthenticationProvider  (which normally validates the client) however, the **user** credential is being passed. I figure that is how it works, which would fail then the ProviderManager, on it's second Iteration would select my custom `DaoAuthenticationProvider` to verify the user credential. Thing is on the first iteration, when it fails it throws that specific error that the ProviderManager would rethrow.

**Comment by dsyer** [comment]
Duplicate on SO: http://stackoverflow.com/questions/28730821/spring-security-fails-jdbcclientdetailsservice-error

**Comment by deanclkclk** [comment]
OK, I'm still getting the same issue after following the suggestion on stackoverflow:

     title>Error 500 Incorrect result size: expected 1, actual 2</title>
     </head>
     <body><h2>HTTP ERROR 500</h2>
     <p>Problem accessing /oauth/token. Reason:
     <pre>    Incorrect result size: expected 1, actual 2</pre></p><h3>Caused by:</h3>      <pre>org.springframework.dao.IncorrectResultSizeDataAccessException: Incorrect result size:  expected 1, actual 2
 	at   org.springframework.dao.support.DataAccessUtils.requiredSingleResult(DataAccessUtils.java:74)
	at org.springframework.jdbc.core.JdbcTemplate.queryForObject(JdbcTemplate.java:812)
	at org.springframework.security.oauth2.provider.token.JdbcTokenStore.getAccessToken(JdbcTokenStore.java:105)
	at org.springframework.security.oauth2.provider.token.DefaultTokenServices.createAccessToken(DefaultTokenServices.java:75)
	at org.springframework.security.oauth2.provider.token.AbstractTokenGranter.getAccessToken(AbstractTokenGranter.java:68)
	at org.springframework.security.oauth2.provider.token.AbstractTokenGranter.grant(AbstractTokenGranter.java:60)
	at org.springframework.security.oauth2.provider.client.ClientCredentialsTokenGranter.grant(ClientCredentialsTokenGranter.java:41)
	at org.springframework.security.oauth2.provider.CompositeTokenGranter.grant(CompositeTokenGranter.java:38)
	at org.springframework.security.oauth2.provider.endpoint.TokenEndpoint.getAccessToken(TokenEndpoint.java:100)
	at sun.reflect.GeneratedMethodAccessor241.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.springframework.web.method.support.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:215)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:132)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:104)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandleMethod(RequestMappingHandlerAdapter.java:749)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:689)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:83)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:938)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:870)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:961)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:863)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:837)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:538)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1352)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:118)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:84)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:113)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:154)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.authentication.www.BasicAuthenticationFilter.doFilter(BasicAuthenticationFilter.java:150)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.oauth2.provider.client.ClientCredentialsTokenEndpointFilter.successfulAuthentication(ClientCredentialsTokenEndpointFilter.java:117)
	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:235)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:87)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:192)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:160)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:344)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:261)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1323)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:476)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:119)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:517)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:225)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:937)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:406)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:183)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:871)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:247)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:149)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:110)
	at org.eclipse.jetty.server.Server.handle(Server.java:346)
	at org.eclipse.jetty.server.HttpConnection.handleRequest(HttpConnection.java:589)
	at org.eclipse.jetty.server.HttpConnection$RequestHandler.content(HttpConnection.java:1065)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:823)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:220)
	at org.eclipse.jetty.server.HttpConnection.handle(HttpConnection.java:411)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:535)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:40)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:529)
	at java.lang.Thread.run(Thread.java:745)

**Comment by dsyer** [comment]
That's nothing to do with the original problem though. You have a duplicate record in your database. I believe you need to manually delete it and then make sure you enable `@Transactional`.

**Comment by deanclkclk** [comment]
@dsyer  OK but, at what component would I enable @Transactional?

**Comment by dsyer** [comment]
Anywhere you like. It's `@EnableTransactionProcessing` (from memory). I won't even try and remember the XML incantation, but it's the same idea, and it's easy to find in the Spring user guide.

**Comment by deanclkclk** [comment]
@dsyer  OK so, I was going to add the @Transactional annotation to my custom grant types on the API:

     
	<beans:bean id="randomTokenGrant" class="com.cointraders.api.grants.RandomTokenGrant">
		<beans:constructor-arg index="0"><beans:value>${api.common.login.oauth.token}</beans:value></beans:constructor-arg>
		<beans:constructor-arg index="1"><beans:value>${user.login.username.param}</beans:value></beans:constructor-arg>
		<beans:constructor-arg index="2"><beans:value>${user.login.password.param}</beans:value></beans:constructor-arg>
		<beans:constructor-arg index="3" ref="authenticationManager2"></beans:constructor-arg>
		<beans:constructor-arg index="4" ref="tokenServices"></beans:constructor-arg>
		<beans:constructor-arg index="5" ref="clientDetails"></beans:constructor-arg>
		<beans:constructor-arg index="6"><beans:value>${api.common.login.oauth.grant_type.two_factor}</beans:value></beans:constructor-arg>
		<beans:constructor-arg index="7" ref="userAccountServiceImpl"></beans:constructor-arg>
	</beans:bean>
	
	<beans:bean id="customPasswordGrant" class="com.cointraders.api.grants.CustomPasswordGrant">
		<beans:constructor-arg index="0" ref="authenticationManager2"></beans:constructor-arg>
		<beans:constructor-arg index="1" ref="tokenServices"></beans:constructor-arg>
		<beans:constructor-arg index="2" ref="clientDetails"></beans:constructor-arg>
		<beans:constructor-arg index="3" ref="userAccountServiceImpl"></beans:constructor-arg>
		<beans:constructor-arg index="4"><beans:value>${api.common.login.oauth.grant_type.custom_password}</beans:value></beans:constructor-arg>
	</beans:bean>


But, just looking at the code for `ClientCredentialsTokenGranter`, there's no  @Transactional annotation there. So I'm thinking if I used the predefined granters, I would have the same issue? Seems to me that the @Transactional annotation should not be there.

**Comment by deanclkclk** [comment]
Found what could work:

http://forum.spring.io/forum/spring-projects/security/oauth/121685-jdbctokenstore-sometimes-stores-too-many-access-tokens

**Comment by dsyer** [comment]
Indeed that would work (and in fact we used that solution in production for a while in Cloud Foundry). The XML in that post is ugly, especially considering `DefaultTokenServices` now already has `@Transactional` methods, and all you should need is to set the isolation level (you can do it in the `DataSource` for instance in a Spring Boot app `spring.datasource.defaultTransactionIsolation=4`, as in `REPEATABLE_READ`, or 5 as in `SERIALIZABLE`, per docs in `java.sql.Connection`).

**Comment by deanclkclk** [comment]
@dsyer thanks. Looking at the example for Spring Oauth 2.0.5, I'm not seeing any xml based configuration like the one existing for 1.0.5. Do you have any example project  using the 2.0.5 version with XML configuration? Thanks in advance.
