### ISSUE TITLE
Using new sslOnly flag in AuthorizationServerSecurityConfigurer ends with IllegalStateException

### ISSUE THREAD

**Issue by marauzog** [spring-projects/spring-security-oauth#638]
We're implementing our own authorization server using spring-security-oauth 2.0.7 and we want to enforce SSL in both authorization and token endpoints.

For the authorization endpoint we have configured channel security, custom filters, etc. using a WebSecurityConfigurerAdapter.

For the token endpoint we could not get access to HttpSecurity to set our own security, so we thought that maybe defining another WebSecurityConfigurerAdapter with an order below 0 we could override the default security defined by the framework. But then we saw that version 2.0.8 was out and a new sslOnly method had been added to AuthorizationServerSecurityConfigurer. So we tried it out, but the result was the following error initializing spring context:

```
GRAVE: Exception sending context initialized event to listener instance of class org.springframework.web.context.ContextLoaderListener
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'springSecurityFilterChain' defined in class org.springframework.security.config.annotation.web.configuration.WebSecurityConfiguration: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [javax.servlet.Filter]: Factory method 'springSecurityFilterChain' threw exception; nested exception is **java.lang.IllegalStateException: Cannot apply org.springframework.security.config.annotation.web.configurers.ChannelSecurityConfigurer@289d53a8 to already built object**
    at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:599)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1111)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1006)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:504)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:476)
    at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:303)
    at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
    at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:299)
    at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194)
    at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:755)
    at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:757)
    at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:480)
    at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:403)
    at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:306)
    at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:106)
    at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4937)
    at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5434)
    at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
    at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1559)
    at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1549)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [javax.servlet.Filter]: Factory method 'springSecurityFilterChain' threw exception; nested exception is java.lang.IllegalStateException: Cannot apply org.springframework.security.config.annotation.web.configurers.ChannelSecurityConfigurer@289d53a8 to already built object
    at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:189)
    at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:588)
    ... 23 more
Caused by: java.lang.IllegalStateException: Cannot apply org.springframework.security.config.annotation.web.configurers.ChannelSecurityConfigurer@289d53a8 to already built object
    at org.springframework.security.config.annotation.AbstractConfiguredSecurityBuilder.add(AbstractConfiguredSecurityBuilder.java:194)
    at org.springframework.security.config.annotation.AbstractConfiguredSecurityBuilder.apply(AbstractConfiguredSecurityBuilder.java:129)
    at org.springframework.security.config.annotation.web.builders.HttpSecurity.getOrApply(HttpSecurity.java:1187)
    at org.springframework.security.config.annotation.web.builders.HttpSecurity.requiresChannel(HttpSecurity.java:875)
    at org.springframework.security.oauth2.config.annotation.web.configurers.AuthorizationServerSecurityConfigurer.configure(AuthorizationServerSecurityConfigurer.java:193)
    at org.springframework.security.oauth2.config.annotation.web.configurers.AuthorizationServerSecurityConfigurer.configure(AuthorizationServerSecurityConfigurer.java:54)
    at org.springframework.security.config.annotation.AbstractConfiguredSecurityBuilder.configure(AbstractConfiguredSecurityBuilder.java:378)
    at org.springframework.security.config.annotation.AbstractConfiguredSecurityBuilder.doBuild(AbstractConfiguredSecurityBuilder.java:328)
    at org.springframework.security.config.annotation.AbstractSecurityBuilder.build(AbstractSecurityBuilder.java:41)
    at org.springframework.security.config.annotation.web.builders.WebSecurity.performBuild(WebSecurity.java:289)
    at org.springframework.security.config.annotation.web.builders.WebSecurity.performBuild(WebSecurity.java:74)
    at org.springframework.security.config.annotation.AbstractConfiguredSecurityBuilder.doBuild(AbstractConfiguredSecurityBuilder.java:332)
    at org.springframework.security.config.annotation.AbstractSecurityBuilder.build(AbstractSecurityBuilder.java:41)
    at org.springframework.security.config.annotation.web.configuration.WebSecurityConfiguration.springSecurityFilterChain(WebSecurityConfiguration.java:105)
    at org.springframework.security.config.annotation.web.configuration.WebSecurityConfiguration$$EnhancerBySpringCGLIB$$641b9dc.CGLIB$springSecurityFilterChain$1(<generated>)
    at org.springframework.security.config.annotation.web.configuration.WebSecurityConfiguration$$EnhancerBySpringCGLIB$$641b9dc$$FastClassBySpringCGLIB$$c4a574fe.invoke(<generated>)
    at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
    at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:309)
    at org.springframework.security.config.annotation.web.configuration.WebSecurityConfiguration$$EnhancerBySpringCGLIB$$641b9dc.springSecurityFilterChain(<generated>)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162)
    ... 24 more
```

This is our code for authorization server configuration:

``` java
@Configuration
@EnableAuthorizationServer
public class AuthorizationServerCfg extends AuthorizationServerConfigurerAdapter {
...
    @Bean
    public PasswordEncoder clientSecretEncoder() {
        return new BCryptPasswordEncoder();
    }

    @Override
    public void configure(AuthorizationServerSecurityConfigurer security) throws Exception {
        security.passwordEncoder(clientSecretEncoder());
                security.checkTokenAccess("isFullyAuthenticated()");
        security.allowFormAuthenticationForClients();
        security.sslOnly();
    }
...
}
```

**Comment by dsyer** [comment]
I tried adding the `sslOnly()` flag to the "vanilla" integration test sample and it worked fine (see c4efb71). Can you put together a minimal sample app that reproduces the problem?

**Comment by ztoufie** [comment]
I've stumbled into what looks like the same problem, whereby I've combined a **WebSecurityConfigurerAdapter** and an **AuthorizationServerConfigurerAdapter** in the same application, together with trying to enable **ssl** in the authorization server. I'm using Spring Boot 1.3.1 and Spring OAuth 2.0.8.

Reading through the Spring OAuth docs, under Enforcing SSL. The doc says to enable the ssl flag on **AuthorizationServerEndpointsConfigurer**, but according to the actual api, the flag is on **AuthorizationServerSecurityConfigurer**.

Assuming that the documentation is incorrect, when I start my spring-boot app, I get;

```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'springSecurityFilterChain' defined in class path resource [org/springframework/security/config/annotation/web/configuration/WebSecurityConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [javax.servlet.Filter]: Factory method 'springSecurityFilterChain' threw exception; nested exception is java.lang.IllegalStateException: Cannot apply org.springframework.security.config.annotation.web.configurers.ChannelSecurityConfigurer@71e3cd8e to already built object
...
Caused by: org.springframework.security.config.annotation.AlreadyBuiltException: This object has already been built
        at org.springframework.security.config.annotation.AbstractSecurityBuilder.build(AbstractSecurityBuilder.java:42)
        at org.springframework.security.config.annotation.web.configuration.WebSecurityConfiguration.springSecurityFilterChain(WebSecurityConfiguration.java:98)
...
```

Looking through your integration test provided above, I notice that you are not enabling **sslOnly()** in the **AuthorizationServerConfigurerAdapter**. I would have expected to see something like this at the very least;

```java
    @Override
    public void configure(AuthorizationServerSecurityConfigurer oauthServer) throws Exception {
        oauthServer
            .sslOnly();
    }
```

Thus the trigger that is causing the exception, is enabling ssl via sslOnly(). If one removes the sslOnly() call, Spring Boot starts as expected when wanting http only endpoints.

Let me know if you require further info.

**Comment by ztoufie** [comment]
Hey Miguel,

Did you ever get this resolved?

**Comment by dsyer** [comment]
Is the `sslOnly(0` setting global in Spring Security (cc @rwinch)? Maybe you only need to set it once (which is what I did in the test)?

**Comment by rwinch** [comment]
`HttpSecurity.requiresChannel()` follows the same rules as `authorizeRequests`. Each `HttpSecurity` instance is attempted to be matched on and the first one "wins". Then all the rules for `requiresChannel` are applied and the first one "wins".

For example, the following will match every request:

```java
http
	.requiresChannel()
		.anyRequest().requiresSecure();
```

Would require the URL to start with /api/secure/

```java
http
	.antMatcher("/api/**")
	.requiresChannel()
		.antMatchers("/secure/**").requiresSecure();
```

**Comment by ztoufie** [comment]
Previously I was using mixed http and https connectors whereby some requests could use either channel and some others could only use the secured one.

I've now resorted to only having one Tomcat connector and using the above to require ALL requests to use the secure channel. That way at least I can have https without having to use sslOnly().

**Comment by dziadeusz** [comment]
I am having the same issue. I have a working Authorization server, yet setting the sslOnly flag causes the above descirbed exception. I do not have any other WebSecurityConfigurerAdapter etc.

**Comment by dziadeusz** [comment]
@rwinch  could you please explain why I cannot simply set the ssl redirection via

` @Override
    public void configure(AuthorizationServerSecurityConfigurer oauthServer) throws Exception {
        oauthServer
            .sslOnly();
    }`

**Comment by djcam** [comment]
I am having the same issue described above. Has there been any further insight on this one?

**Comment by dziadeusz** [comment]
Not that I know of. At least someone could explain how to provide a custom WebSecurityConfigurerAdapter TOGETHER with AuthorizationServerConfigurerAdapter. As for now if I try to provide websecurity configuration in a separate bean the authorization server config is overriden (ignored?).

**Comment by dziadeusz** [comment]
@dsyer The example you linked does not use the sslOnly flag. Would you be so kind as to provide one? I am able to secure the resource server endpoints with requiresChannel though the AuthorizationServer seems not to be configurable this way.

**Comment by astropcrb** [comment]
Also having this issue. Curious is a resolution was found.

**Comment by jgrandja** [comment]
Here is a working [sample](https://github.com/jgrandja/spring-security-oauth-sample/tree/gh-638-secure-token-endpoints) that provides a temporary workaround until this bug is fixed.

In a nutshell, follow these steps to enable secure channel on the token endpoints.

1) Create this custom `AuthorizationServerSecurityConfiguration` and enable secure channel on the token endpoints.

```
public class CustomAuthorizationServerSecurityConfiguration extends AuthorizationServerSecurityConfiguration {

	@Override
	protected void configure(HttpSecurity http) throws Exception {
		super.configure(http);

		http
			.requiresChannel()
				.antMatchers("/oauth/token", "/oauth/token_key", "/oauth/check_token")
					.requiresSecure();
	}
}
```

2) Create your custom `@EnableAuthorizationServer` (without using the annotation) and import `AuthorizationServerEndpointsConfiguration` and `CustomAuthorizationServerSecurityConfiguration` (as above).
 **NOTE:** DO NOT use `@EnableAuthorizationServer`

```
@Configuration
//@EnableAuthorizationServer
@Import({AuthorizationServerEndpointsConfiguration.class, CustomAuthorizationServerSecurityConfiguration.class})
public class AuthorizationServerConfig extends AuthorizationServerConfigurerAdapter {

...

}
```
