### ISSUE TITLE
RedisTokenStoreTests fail on Windows due to embedded Redis not working on Windows

### ISSUE THREAD

**Issue by BjoernSt** [spring-projects/spring-security-oauth#650]
Hello everyone,
I tried to install and run the samples as per the "Getting started" section in different ways and always run into the same errors during the maven test phase when running `mvn install -P bootstrap`
Here are some of the variants I tried:
* Downloaded v.2.0.9-SNAPSHOT with Eclipse egit
  * changed to tagged release v2.0.8
  * changed to tagged release v2.0.7
  * changed to tagged release v2.0.6
* Downloaded the 2.0.9-SNAPSHOT from master as a zip
* Downloaded 2.0.8 release version as a zip
* cleared the local maven repository (in fact referenced a blank dir in the maven settings.xml)
* used to different maven versions (3.0.5 and 3.3.3) 
* used three different JDKs

The outcome of the test phase was always this:
````
[...]
Results :

Tests in error: 
  testExpiringRefreshToken(org.springframework.security.oauth2.provider.token.store.redis.RedisTokenStoreTests)
  testExpiringRefreshToken(org.springframework.security.oauth2.provider.token.store.redis.RedisTokenStoreTests)
  testExpiringAccessToken(org.springframework.security.oauth2.provider.token.store.redis.RedisTokenStoreTests)
  testExpiringAccessToken(org.springframework.security.oauth2.provider.token.store.redis.RedisTokenStoreTests)
  testStoreRefreshToken(org.springframework.security.oauth2.provider.token.store.redis.RedisTokenStoreTests)
  testStoreRefreshToken(org.springframework.security.oauth2.provider.token.store.redis.RedisTokenStoreTests)
  testRetrieveAccessToken(org.springframework.security.oauth2.provider.token.store.redis.RedisTokenStoreTests)
  testRetrieveAccessToken(org.springframework.security.oauth2.provider.token.store.redis.RedisTokenStoreTests)
  testReadingRefreshTokenForTokenThatDoesNotExist(org.springframework.security.oauth2.provider.token.store.redis.RedisTokenStoreTests)
  testReadingRefreshTokenForTokenThatDoesNotExist(org.springframework.security.oauth2.provider.token.store.redis.RedisTokenStoreTests)
  testFindAccessTokensByClientId(org.springframework.security.oauth2.provider.token.store.redis.RedisTokenStoreTests)
  testFindAccessTokensByClientId(org.springframework.security.oauth2.provider.token.store.redis.RedisTokenStoreTests)
  testFindAccessTokensByClientIdAndUserName(org.springframework.security.oauth2.provider.token.store.redis.RedisTokenStoreTests)
  testFindAccessTokensByClientIdAndUserName(org.springframework.security.oauth2.provider.token.store.redis.RedisTokenStoreTests)
  testStoreAccessToken(org.springframework.security.oauth2.provider.token.store.redis.RedisTokenStoreTests)
  testStoreAccessToken(org.springframework.security.oauth2.provider.token.store.redis.RedisTokenStoreTests)
  testRemovedTokenCannotBeFoundByUsername(org.springframework.security.oauth2.provider.token.store.redis.RedisTokenStoreTests)
  testRemovedTokenCannotBeFoundByUsername(org.springframework.security.oauth2.provider.token.store.redis.RedisTokenStoreTests)
  testReadingAccessTokenForTokenThatDoesNotExist(org.springframework.security.oauth2.provider.token.store.redis.RedisTokenStoreTests)
  testReadingAccessTokenForTokenThatDoesNotExist(org.springframework.security.oauth2.provider.token.store.redis.RedisTokenStoreTests)
  testRemoveRefreshToken(org.springframework.security.oauth2.provider.token.store.redis.RedisTokenStoreTests)
  testRemoveRefreshToken(org.springframework.security.oauth2.provider.token.store.redis.RedisTokenStoreTests)
  testReadingAuthenticationForTokenThatDoesNotExist(org.springframework.security.oauth2.provider.token.store.redis.RedisTokenStoreTests)
  testReadingAuthenticationForTokenThatDoesNotExist(org.springframework.security.oauth2.provider.token.store.redis.RedisTokenStoreTests)
  testStoreAccessTokenTwice(org.springframework.security.oauth2.provider.token.store.redis.RedisTokenStoreTests)
  testStoreAccessTokenTwice(org.springframework.security.oauth2.provider.token.store.redis.RedisTokenStoreTests)
  testRefreshTokenIsNotStoredDuringAccessToken(org.springframework.security.oauth2.provider.token.store.redis.RedisTokenStoreTests)
  testRefreshTokenIsNotStoredDuringAccessToken(org.springframework.security.oauth2.provider.token.store.redis.RedisTokenStoreTests)
  testGetAccessTokenForDeletedUser(org.springframework.security.oauth2.provider.token.store.redis.RedisTokenStoreTests)
  testGetAccessTokenForDeletedUser(org.springframework.security.oauth2.provider.token.store.redis.RedisTokenStoreTests)

Tests run: 610, Failures: 0, Errors: 30, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] OAuth for Spring Security .......................... SUCCESS [  2.044 s]
[INFO] OAuth 1(a) for Spring Security ..................... SUCCESS [ 20.215 s]
[INFO] OAuth2 for Spring Security ......................... FAILURE [ 29.350 s]
[INFO] spring-oauth2-tests ................................ SKIPPED
[INFO] spring-oauth2-tests-common ......................... SKIPPED
[INFO] spring-oauth2-tests-vanilla ........................ SKIPPED
[INFO] spring-oauth2-tests-mappings ....................... SKIPPED
[INFO] spring-oauth2-tests-form ........................... SKIPPED
[INFO] spring-oauth2-tests-jwt ............................ SKIPPED
[INFO] spring-oauth2-tests-approval ....................... SKIPPED
[INFO] spring-oauth2-tests-jdbc ........................... SKIPPED
[INFO] spring-oauth-tests-custom-grant .................... SKIPPED
[INFO] spring-oauth2-tests-multi .......................... SKIPPED
[INFO] spring-oauth2-tests-client ......................... SKIPPED
[INFO] spring-oauth2-tests-resource ....................... SKIPPED
[INFO] spring-oauth2-tests-custom-authentication .......... SKIPPED
[INFO] spring-oauth2-tests-xml ............................ SKIPPED
[INFO] spring-oauth2-tests-xml-common ..................... SKIPPED
[INFO] spring-oauth2-tests-xml-vanilla .................... SKIPPED
[INFO] spring-oauth2-tests-xml-mappings ................... SKIPPED
[INFO] spring-oauth2-tests-xml-form ....................... SKIPPED
[INFO] spring-oauth2-tests-xml-jwt ........................ SKIPPED
[INFO] spring-oauth2-tests-xml-approval ................... SKIPPED
[INFO] spring-oauth2-tests-xml-jdbc ....................... SKIPPED
[INFO] spring-oauth2-tests-xml-client ..................... SKIPPED
[INFO] OAuth for Spring Security - Integration Tests ...... SKIPPED
[INFO] OAuth for Spring Security - Sparklr (OAuth 1 Provider Example) SKIPPED
[INFO] OAuth for Spring Security - Tonr (OAuth 1 Consumer Example) SKIPPED
[INFO] OAuth for Spring Security - Sparklr2 (OAuth 2 Provider Example) SKIPPED
[INFO] OAuth for Spring Security - Tonr2 (OAuth 2 Client Example) SKIPPED
[INFO] OAuth for Spring Security - Samples ................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 52.860 s
[INFO] Finished at: 2015-12-03T16:53:58+01:00
[INFO] Final Memory: 59M/172M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project spring-security-oauth2: There are test failures.
[...]
````

Here are some of the exceptions I encountered during the tests:
````
[...]
testExpiringRefreshToken(org.springframework.security.oauth2.provider.token.store.redis.RedisTokenStoreTests)  Time elapsed: 0.008 sec  <<< ERROR!
java.lang.NullPointerException
	at java.util.Objects.requireNonNull(Objects.java:203)
	at java.nio.file.Files.copy(Files.java:2984)
	at redis.embedded.RedisServer.extractExecutableFromJar(RedisServer.java:85)
	at redis.embedded.RedisServer.<init>(RedisServer.java:69)
	at redis.embedded.RedisServer.<init>(RedisServer.java:63)
	at redis.embedded.RedisServer.<init>(RedisServer.java:55)
	at org.springframework.security.oauth2.provider.token.store.redis.RedisTokenStoreTests.setup(RedisTokenStoreTests.java:40)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

testExpiringRefreshToken(org.springframework.security.oauth2.provider.token.store.redis.RedisTokenStoreTests)  Time elapsed: 0.008 sec  <<< ERROR!
java.lang.NullPointerException
	at org.springframework.security.oauth2.provider.token.store.redis.RedisTokenStoreTests.tearDown(RedisTokenStoreTests.java:49)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:33)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

testExpiringAccessToken(org.springframework.security.oauth2.provider.token.store.redis.RedisTokenStoreTests)  Time elapsed: 0 sec  <<< ERROR!
java.lang.NullPointerException
	at java.util.Objects.requireNonNull(Objects.java:203)
	at java.nio.file.Files.copy(Files.java:2984)
	at redis.embedded.RedisServer.extractExecutableFromJar(RedisServer.java:85)
	at redis.embedded.RedisServer.<init>(RedisServer.java:69)
	at redis.embedded.RedisServer.<init>(RedisServer.java:63)
	at redis.embedded.RedisServer.<init>(RedisServer.java:55)
	at org.springframework.security.oauth2.provider.token.store.redis.RedisTokenStoreTests.setup(RedisTokenStoreTests.java:40)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
[...]
````
Since obviously noone else is encountering this behaviour I must do something really wrong but I dont have a clue what it could be. 

Hoping for help,
 Björn

**Comment by rwinch** [comment]
I think this is actually an issue with embedded Redis on your operating system (OS). We tried to leverage embedded Redis in Spring Session, but it caused to many problems for various OS's. See https://github.com/spring-projects/spring-session/issues/121#issuecomment-124653443

**Comment by BjoernSt** [comment]
Hi Rob,
many thanks for your fast reply. 
Honestly, I had to look up what Redis is at all. I tested Spring OAuth on two different machines - one running with Windows 8.1 and one with Windows 7 and on both I never installed a Redis server (at least not knowingly). 
Does this mean that both OSs are running an embedded Redis instance by default? Then I would assume I am not the only one with the problem that I described. 
Is there a quick check to identify the presence (or absence) of a Redis instance on windows?

**Comment by rwinch** [comment]
The build tries to deploy a Redis instance automatically, but likely will not work for Windows. If we updated the embedded redis dependency it might work for Windows 64 bit, but I have not tried it recently.

In short, these tests probably need to be fixed to ensure that they pass for any OS.

**Comment by BjoernSt** [comment]
So am I supposed to to run `mvn -DskipTests install`? That would create the jar but probably I would run into the same exception at runtime later, wouldn't I? 
I apologize for asking all these likely stupid questions.

**Comment by rwinch** [comment]
@BjoernSt Not a dumb question at all. I'm am here to serve :)

You should not actually need to install if you add the following maven repository to the maven sample pom:

```xml
               <repository>
			<id>spring-snapshot</id>
			<name>Spring Framework Snapshot Repository</name>
			<url>http://maven.springframework.org/snapshot</url>
		</repository>
```

Alternatively, you can skip the tests.

So long as you are not trying to run code that stores the token in Redis, you would not get that error when you run the sample.

Cheers,
Rob

**Comment by BjoernSt** [comment]
Rob, thanks a lot for your quick help. I appreciate it!

Still think that I am bit dumber than other people who seem not to encounter this problem ;-)

**Comment by rwinch** [comment]
> Still think that I am bit dumber than other people who seem not to encounter this problem ;-)

On the contrary, I think you are smart enough to bring it up! I'm going to reopen this as it is a legitimate bug. Thanks again for reporting it :)

**Comment by jonjarvis** [comment]
I ran into this same issue on Windows 7. Do the Sparklr and Tonr2 samples for OAuth2 utilize the built-in redis? I was able to skip tests installing the 2.0.8 release and install, but neither of the samples worked at the browser address after following the mvn run:tomcat7 instructions.

**Comment by dsyer** [comment]
Those samples do not use redis, so if you have issues they are unrelated.

**Comment by dween** [comment]
I see the same error messages on Win10 with the project downloaded today (3/27/2017) - I guess the issue has not yet been resolved?

**Comment by dcurrytca** [comment]
This isn't just Windows. I'm having the same issue on CentOS 7.2.

**Comment by dcurrytca** [comment]
Which begs the question: If it won't work on Windows and CentOS, what will it work on?

**Comment by dsyer** [comment]
I would have thought any Linux would work. Maybe you have a bad jar, or a firewall preventing you from downloading or starting the embedded server.

**Comment by dcurrytca** [comment]
I disabled the firewall and SELinux (standard practice for a development box). I've tried multiple builds from scratch on different tags, so I'm not sure how it could be a bad JAR. I'm using Vagrant, so I could use a different Linux base box pretty easily. What distro do the developers generally use?

**Comment by dcurrytca** [comment]
I confirmed that on CentOS 7.2 with 2.1.0.RELEASE and master, the following allows me to run the samples, although I had to skip the tests:

mvn -P bootstrap -DskipTests install
cd samples/oauth2/tonr
mvn tomcat7:run
http://localhost:8080/tonr2/
