### ISSUE TITLE
No suitable constructor found for type OAuth2Authentication

### ISSUE THREAD

**Issue by n0mer** [spring-projects/spring-security-oauth#663]
When de-serializing Authentication using JdbcTokenStore custom custom Jackson - getting this message.

com.fasterxml.jackson.databind.JsonMappingException: No suitable constructor found for type [simple type, class org.springframework.security.oauth2.provider.OAuth2Authentication]: can not instantiate from JSON object (missing default constructor or creator, or perhaps need to add/enable type information?)
 at [Source: [B@3f6a0353; line: 1, column: 2]
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:148)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1106)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:294)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:131)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3702)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2807)

**Comment by jgrandja** [comment]
@n0mer Have you been able to resolve this issue? I'm going to close this for now assuming you have solved it since it's been a while you posted. If you are still having this issue please re-open and we will discuss. Thanks.
