### ISSUE TITLE
More than 1 scope causes authentication to fail

### ISSUE THREAD

**Issue by michaelwoodson** [spring-projects/spring-security-oauth#722]
I had authentication working with 1 scope, then when I added an additional scope authentication started failing during access token extraction with a rather cryptic exception:

```
Caused by: com.fasterxml.jackson.databind.JsonMappingException: No content to map due to end-of-input
 at [Source: java.io.PushbackInputStream@88948e5; line: 1, column: 244]
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:148) ~[jackson-databind-2.6.5.jar:2.6.5]
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3781) ~[jackson-databind-2.6.5.jar:2.6.5]
	at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:3694) ~[jackson-databind-2.6.5.jar:2.6.5]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2005) ~[jackson-databind-2.6.5.jar:2.6.5]
	at com.fasterxml.jackson.core.JsonParser.readValueAs(JsonParser.java:1506) ~[jackson-core-2.6.5.jar:2.6.5]
	at org.springframework.security.oauth2.common.OAuth2AccessTokenJackson2Deserializer.deserialize(OAuth2AccessTokenJackson2Deserializer.java:87) ~[spring-security-oauth2-2.0.9.RELEASE.jar:na]
	at org.springframework.security.oauth2.common.OAuth2AccessTokenJackson2Deserializer.deserialize(OAuth2AccessTokenJackson2Deserializer.java:45) ~[spring-security-oauth2-2.0.9.RELEASE.jar:na]
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3736) ~[jackson-databind-2.6.5.jar:2.6.5]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2810) ~[jackson-databind-2.6.5.jar:2.6.5]
	at org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.readJavaType(AbstractJackson2HttpMessageConverter.java:222) ~[spring-web-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	... 68 common frames omitted
```

I was able to isolate the issue to the OAuth2AccessTokenJackson2Deserializer.  Something about the extra scope is tripping up the deserializer.  Not sure exactly what is going on, saw some comments in the code implying the expected format for multiple scopes to be space separated `"scope1 scope2"` but the endpoint I am trying to talk to (twitch kraken) is formatting them as json `["scope1","scope2"]`.  For some reason it still reads ok with 1 scope but breaks with 2.

This code demonstrates the problem and might be a starting point for a unit test.  Notice the only difference is the extra value for the scope that causes an exception to be thrown.  Since this code is parsing a string instead of an input stream the exception is more meaningful.

```
	public static void main(String[] args) throws JsonParseException, JsonMappingException, IOException {
		ObjectMapper mapper = new ObjectMapper();
		mapper.registerSubtypes(OAuth2AccessToken.class);
		System.out.println("parsing works with one scope");
		mapper.readValue("{\"access_token\":\"accesstoken\",\"refresh_token\":\"refreshtoken\",\"scope\":[\"user_read\"]}", OAuth2AccessToken.class);
		System.out.println("parsing fails with two scopes");
		mapper.readValue("{\"access_token\":\"accesstoken\",\"refresh_token\":\"refreshtoken\",\"scope\":[\"user_read\",\"user_subscriptions\"]}", OAuth2AccessToken.class);
		System.out.println("never makes it here.");
	}
```

Found using spring-security-oauth2 2.0.9 and jackson 2.6.5.

**Comment by rwinch** [comment]
Relates to #745
