### ISSUE TITLE
use equals instead "==" in JwtAccessTokenConverter.afterPropertiesSet 

### ISSUE THREAD

**Issue by Rebyrg** [spring-projects/spring-security-oauth#858]
JwtAccessTokenConverter.afterPropertiesSet  thrown unecpected exception.

My application.properties contains:
`security.oauth2.resource.jwt.key-value: "${JWT_SIGN_KEY:password}"`

When I run my application without setting JWT_SIGN_KEY env everything works fine.
But when I set JWT_SIGN_KEY env before I run my application then exception is thrown during spring initialization:

```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'jwtTokenEnhancer' defined in class path resource [org/springframework/boot/autoconfigure/security/oauth2/resource/ResourceServerTokenServicesConfiguration$JwtTokenServicesConfiguration.class]: Invocation of init method failed; nested exception is java.lang.IllegalStateException: For MAC signing you do not need to specify the verifier key separately, and if you do it must match the signing key
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1583)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:545)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
        at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:381)
        at org.springframework.boot.autoconfigure.security.oauth2.resource.ResourceServerTokenServicesConfiguration$JwtTokenServicesConfiguration$$EnhancerBySpringCGLIB$$e32d3605.jwtTokenEnhancer(<generated>)
        at org.springframework.boot.autoconfigure.security.oauth2.resource.ResourceServerTokenServicesConfiguration$JwtTokenServicesConfiguration.jwtTokenStore(ResourceServerTokenServicesConfiguration.java:243)
```

My ResourceServiceConfig:

```
@Configuration
public class ResourceServiceConfig extends ResourceServerConfigurerAdapter {
    @Value("${security.oauth2.resource.jwt.key-value}")
    private String tokenSignKey;
    @Override
    public void configure(ResourceServerSecurityConfigurer resources) throws Exception {
        resources.tokenServices(tokenServices());
    }
    @Bean
    @Primary
    public DefaultTokenServices tokenServices() {
        DefaultTokenServices defaultTokenServices = new DefaultTokenServices();
        defaultTokenServices.setTokenStore(tokenStore());
        return defaultTokenServices;
    }
    @Bean
    public TokenStore tokenStore() {
        return new JwtTokenStore(jwtAccessTokenConverter());
    }
    @Bean
    public JwtAccessTokenConverter jwtAccessTokenConverter() {
        JwtAccessTokenConverter converter = new JwtAccessTokenConverter();
        converter.setSigningKey(tokenSignKey);
        converter.setAccessTokenConverter(accessTokenConverter());
        return converter;
    }
    @Bean
    public AccessTokenConverter accessTokenConverter() {
        DefaultAccessTokenConverter converter = new DefaultAccessTokenConverter();
        converter.setUserTokenConverter(userAuthenticationConverter());
        return converter;
    }
    @Bean
    public UserAuthenticationConverter userAuthenticationConverter() {
        return new MyUserAuthenticationConverter();
    }
}
```

My application class is annotated by `@SpringBootApplication, @EnableAspectJAutoProxy, @EnableResourceServer`

**Comment by Rebyrg** [comment]
.
