### ISSUE TITLE
Failed to deserialize authentication for ... (java.lang.ClassNotFoundException) + hibernate

### ISSUE THREAD

**Issue by handioq** [spring-projects/spring-security-oauth#861]
Hello there.

I'm using JDBC TokenStore and all works fine, but today i make a package refactor and relocated my Entities to another package. And after this on runtime (when receiving token) i got an error:

```
2016-10-01 20:14:20.265  WARN 9576 --- [nio-8080-exec-1] o.s.s.o.p.token.store.JdbcTokenStore     : Failed to deserialize authentication for 842cb86e-879f-43bf-a121-ba47eb1b87f0

java.lang.IllegalArgumentException: java.lang.ClassNotFoundException: com.github.handioq.shopapp.model.User
	at org.springframework.security.oauth2.common.util.SerializationUtils.deserialize(SerializationUtils.java:43) ~[spring-security-oauth2-2.0.9.RELEASE.jar:na]
	at org.springframework.security.oauth2.provider.token.store.JdbcTokenStore.deserializeAuthentication(JdbcTokenStore.java:405) [spring-security-oauth2-2.0.9.RELEASE.jar:na]

....

Caused by: java.lang.ClassNotFoundException: com.github.handioq.shopapp.model.User
```

I already tried to clear the project using maven, restart idea, rebuild the project and so on, but it there is no results..

Any suggestions? 
I think that hibernate not able to update Entities and therefore there is an error, but how to fix it?

**Comment by handioq** [comment]
Okay, i decide that maybe there is some bug or smth like this.
I drop my tables, move my Entities to another package and it is works fine.

And for additional, [click here](http://stackoverflow.com/questions/23366226/spring-boot-w-jpa-move-entity-to-different-package) to get some info about @EntityScan annotation.
